// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_CustomGameFollowMaster : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_CustomGameFollowMaster GetRootAsCQ_CustomGameFollowMaster(ByteBuffer _bb) { return GetRootAsCQ_CustomGameFollowMaster(_bb, new CQ_CustomGameFollowMaster()); }
  public static CQ_CustomGameFollowMaster GetRootAsCQ_CustomGameFollowMaster(ByteBuffer _bb, CQ_CustomGameFollowMaster obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_CustomGameFollowMaster __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string MasterNick { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMasterNickBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMasterNickBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMasterNickArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Lobby.CQ_CustomGameFollowMaster> CreateCQ_CustomGameFollowMaster(FlatBufferBuilder builder,
      StringOffset MasterNickOffset = default(StringOffset)) {
    builder.StartTable(1);
    CQ_CustomGameFollowMaster.AddMasterNick(builder, MasterNickOffset);
    return CQ_CustomGameFollowMaster.EndCQ_CustomGameFollowMaster(builder);
  }

  public static void StartCQ_CustomGameFollowMaster(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMasterNick(FlatBufferBuilder builder, StringOffset MasterNickOffset) { builder.AddOffset(0, MasterNickOffset.Value, 0); }
  public static Offset<Lobby.CQ_CustomGameFollowMaster> EndCQ_CustomGameFollowMaster(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_CustomGameFollowMaster>(o);
  }
  public CQ_CustomGameFollowMasterT UnPack() {
    var _o = new CQ_CustomGameFollowMasterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_CustomGameFollowMasterT _o) {
    _o.MasterNick = this.MasterNick;
  }
  public static Offset<Lobby.CQ_CustomGameFollowMaster> Pack(FlatBufferBuilder builder, CQ_CustomGameFollowMasterT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_CustomGameFollowMaster>);
    var _MasterNick = _o.MasterNick == null ? default(StringOffset) : builder.CreateString(_o.MasterNick);
    return CreateCQ_CustomGameFollowMaster(
      builder,
      _MasterNick);
  }
}

public class CQ_CustomGameFollowMasterT
{
  public string MasterNick { get; set; }

  public CQ_CustomGameFollowMasterT() {
    this.MasterNick = null;
  }
}


}
