// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_CraftMake : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_CraftMake GetRootAsCQ_CraftMake(ByteBuffer _bb) { return GetRootAsCQ_CraftMake(_bb, new CQ_CraftMake()); }
  public static CQ_CraftMake GetRootAsCQ_CraftMake(ByteBuffer _bb, CQ_CraftMake obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_CraftMake __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CraftID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CraftCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }

  public static Offset<Lobby.CQ_CraftMake> CreateCQ_CraftMake(FlatBufferBuilder builder,
      int CraftID = 0,
      int CraftCount = 1) {
    builder.StartTable(2);
    CQ_CraftMake.AddCraftCount(builder, CraftCount);
    CQ_CraftMake.AddCraftID(builder, CraftID);
    return CQ_CraftMake.EndCQ_CraftMake(builder);
  }

  public static void StartCQ_CraftMake(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCraftID(FlatBufferBuilder builder, int CraftID) { builder.AddInt(0, CraftID, 0); }
  public static void AddCraftCount(FlatBufferBuilder builder, int CraftCount) { builder.AddInt(1, CraftCount, 1); }
  public static Offset<Lobby.CQ_CraftMake> EndCQ_CraftMake(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_CraftMake>(o);
  }
  public CQ_CraftMakeT UnPack() {
    var _o = new CQ_CraftMakeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_CraftMakeT _o) {
    _o.CraftID = this.CraftID;
    _o.CraftCount = this.CraftCount;
  }
  public static Offset<Lobby.CQ_CraftMake> Pack(FlatBufferBuilder builder, CQ_CraftMakeT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_CraftMake>);
    return CreateCQ_CraftMake(
      builder,
      _o.CraftID,
      _o.CraftCount);
  }
}

public class CQ_CraftMakeT
{
  public int CraftID { get; set; }
  public int CraftCount { get; set; }

  public CQ_CraftMakeT() {
    this.CraftID = 0;
    this.CraftCount = 1;
  }
}


}
