// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_CustomGameKickMember : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_CustomGameKickMember GetRootAsCQ_CustomGameKickMember(ByteBuffer _bb) { return GetRootAsCQ_CustomGameKickMember(_bb, new CQ_CustomGameKickMember()); }
  public static CQ_CustomGameKickMember GetRootAsCQ_CustomGameKickMember(ByteBuffer _bb, CQ_CustomGameKickMember obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_CustomGameKickMember __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoomID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoomIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRoomIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoomIDArray() { return __p.__vector_as_array<byte>(4); }
  public int KickMemberUID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_CustomGameKickMember> CreateCQ_CustomGameKickMember(FlatBufferBuilder builder,
      StringOffset RoomIDOffset = default(StringOffset),
      int KickMemberUID = 0) {
    builder.StartTable(2);
    CQ_CustomGameKickMember.AddKickMemberUID(builder, KickMemberUID);
    CQ_CustomGameKickMember.AddRoomID(builder, RoomIDOffset);
    return CQ_CustomGameKickMember.EndCQ_CustomGameKickMember(builder);
  }

  public static void StartCQ_CustomGameKickMember(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddRoomID(FlatBufferBuilder builder, StringOffset RoomIDOffset) { builder.AddOffset(0, RoomIDOffset.Value, 0); }
  public static void AddKickMemberUID(FlatBufferBuilder builder, int KickMemberUID) { builder.AddInt(1, KickMemberUID, 0); }
  public static Offset<Lobby.CQ_CustomGameKickMember> EndCQ_CustomGameKickMember(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_CustomGameKickMember>(o);
  }
  public CQ_CustomGameKickMemberT UnPack() {
    var _o = new CQ_CustomGameKickMemberT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_CustomGameKickMemberT _o) {
    _o.RoomID = this.RoomID;
    _o.KickMemberUID = this.KickMemberUID;
  }
  public static Offset<Lobby.CQ_CustomGameKickMember> Pack(FlatBufferBuilder builder, CQ_CustomGameKickMemberT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_CustomGameKickMember>);
    var _RoomID = _o.RoomID == null ? default(StringOffset) : builder.CreateString(_o.RoomID);
    return CreateCQ_CustomGameKickMember(
      builder,
      _RoomID,
      _o.KickMemberUID);
  }
}

public class CQ_CustomGameKickMemberT
{
  public string RoomID { get; set; }
  public int KickMemberUID { get; set; }

  public CQ_CustomGameKickMemberT() {
    this.RoomID = null;
    this.KickMemberUID = 0;
  }
}


}
