// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_EnterTrainingRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_EnterTrainingRoom GetRootAsCQ_EnterTrainingRoom(ByteBuffer _bb) { return GetRootAsCQ_EnterTrainingRoom(_bb, new CQ_EnterTrainingRoom()); }
  public static CQ_EnterTrainingRoom GetRootAsCQ_EnterTrainingRoom(ByteBuffer _bb, CQ_EnterTrainingRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_EnterTrainingRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCQ_EnterTrainingRoom(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.CQ_EnterTrainingRoom> EndCQ_EnterTrainingRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_EnterTrainingRoom>(o);
  }
  public CQ_EnterTrainingRoomT UnPack() {
    var _o = new CQ_EnterTrainingRoomT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_EnterTrainingRoomT _o) {
  }
  public static Offset<Lobby.CQ_EnterTrainingRoom> Pack(FlatBufferBuilder builder, CQ_EnterTrainingRoomT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_EnterTrainingRoom>);
    StartCQ_EnterTrainingRoom(builder);
    return EndCQ_EnterTrainingRoom(builder);
  }
}

public class CQ_EnterTrainingRoomT
{

  public CQ_EnterTrainingRoomT() {
  }
}


}
