// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_EntitlementList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_EntitlementList GetRootAsCQ_EntitlementList(ByteBuffer _bb) { return GetRootAsCQ_EntitlementList(_bb, new CQ_EntitlementList()); }
  public static CQ_EntitlementList GetRootAsCQ_EntitlementList(ByteBuffer _bb, CQ_EntitlementList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_EntitlementList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCQ_EntitlementList(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.CQ_EntitlementList> EndCQ_EntitlementList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_EntitlementList>(o);
  }
  public CQ_EntitlementListT UnPack() {
    var _o = new CQ_EntitlementListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_EntitlementListT _o) {
  }
  public static Offset<Lobby.CQ_EntitlementList> Pack(FlatBufferBuilder builder, CQ_EntitlementListT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_EntitlementList>);
    StartCQ_EntitlementList(builder);
    return EndCQ_EntitlementList(builder);
  }
}

public class CQ_EntitlementListT
{

  public CQ_EntitlementListT() {
  }
}


}
