// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_FriendChatRoomList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_FriendChatRoomList GetRootAsCQ_FriendChatRoomList(ByteBuffer _bb) { return GetRootAsCQ_FriendChatRoomList(_bb, new CQ_FriendChatRoomList()); }
  public static CQ_FriendChatRoomList GetRootAsCQ_FriendChatRoomList(ByteBuffer _bb, CQ_FriendChatRoomList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_FriendChatRoomList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCQ_FriendChatRoomList(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.CQ_FriendChatRoomList> EndCQ_FriendChatRoomList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_FriendChatRoomList>(o);
  }
  public CQ_FriendChatRoomListT UnPack() {
    var _o = new CQ_FriendChatRoomListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_FriendChatRoomListT _o) {
  }
  public static Offset<Lobby.CQ_FriendChatRoomList> Pack(FlatBufferBuilder builder, CQ_FriendChatRoomListT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_FriendChatRoomList>);
    StartCQ_FriendChatRoomList(builder);
    return EndCQ_FriendChatRoomList(builder);
  }
}

public class CQ_FriendChatRoomListT
{

  public CQ_FriendChatRoomListT() {
  }
}


}
