// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_GuideMissionStepReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_GuideMissionStepReward GetRootAsCQ_GuideMissionStepReward(ByteBuffer _bb) { return GetRootAsCQ_GuideMissionStepReward(_bb, new CQ_GuideMissionStepReward()); }
  public static CQ_GuideMissionStepReward GetRootAsCQ_GuideMissionStepReward(ByteBuffer _bb, CQ_GuideMissionStepReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_GuideMissionStepReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int StepID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_GuideMissionStepReward> CreateCQ_GuideMissionStepReward(FlatBufferBuilder builder,
      int StepID = 0) {
    builder.StartTable(1);
    CQ_GuideMissionStepReward.AddStepID(builder, StepID);
    return CQ_GuideMissionStepReward.EndCQ_GuideMissionStepReward(builder);
  }

  public static void StartCQ_GuideMissionStepReward(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStepID(FlatBufferBuilder builder, int StepID) { builder.AddInt(0, StepID, 0); }
  public static Offset<Lobby.CQ_GuideMissionStepReward> EndCQ_GuideMissionStepReward(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_GuideMissionStepReward>(o);
  }
  public CQ_GuideMissionStepRewardT UnPack() {
    var _o = new CQ_GuideMissionStepRewardT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_GuideMissionStepRewardT _o) {
    _o.StepID = this.StepID;
  }
  public static Offset<Lobby.CQ_GuideMissionStepReward> Pack(FlatBufferBuilder builder, CQ_GuideMissionStepRewardT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_GuideMissionStepReward>);
    return CreateCQ_GuideMissionStepReward(
      builder,
      _o.StepID);
  }
}

public class CQ_GuideMissionStepRewardT
{
  public int StepID { get; set; }

  public CQ_GuideMissionStepRewardT() {
    this.StepID = 0;
  }
}


}
