// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_HeroChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_HeroChange GetRootAsCQ_HeroChange(ByteBuffer _bb) { return GetRootAsCQ_HeroChange(_bb, new CQ_HeroChange()); }
  public static CQ_HeroChange GetRootAsCQ_HeroChange(ByteBuffer _bb, CQ_HeroChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_HeroChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int HeroID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_HeroChange> CreateCQ_HeroChange(FlatBufferBuilder builder,
      int HeroID = 0) {
    builder.StartTable(1);
    CQ_HeroChange.AddHeroID(builder, HeroID);
    return CQ_HeroChange.EndCQ_HeroChange(builder);
  }

  public static void StartCQ_HeroChange(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(0, HeroID, 0); }
  public static Offset<Lobby.CQ_HeroChange> EndCQ_HeroChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_HeroChange>(o);
  }
  public CQ_HeroChangeT UnPack() {
    var _o = new CQ_HeroChangeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_HeroChangeT _o) {
    _o.HeroID = this.HeroID;
  }
  public static Offset<Lobby.CQ_HeroChange> Pack(FlatBufferBuilder builder, CQ_HeroChangeT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_HeroChange>);
    return CreateCQ_HeroChange(
      builder,
      _o.HeroID);
  }
}

public class CQ_HeroChangeT
{
  public int HeroID { get; set; }

  public CQ_HeroChangeT() {
    this.HeroID = 0;
  }
}


}
