// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_HeroSkinPresetSave : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_HeroSkinPresetSave GetRootAsCQ_HeroSkinPresetSave(ByteBuffer _bb) { return GetRootAsCQ_HeroSkinPresetSave(_bb, new CQ_HeroSkinPresetSave()); }
  public static CQ_HeroSkinPresetSave GetRootAsCQ_HeroSkinPresetSave(ByteBuffer _bb, CQ_HeroSkinPresetSave obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_HeroSkinPresetSave __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int HeroID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public byte SlotID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string PresetName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPresetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPresetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPresetNameArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<Lobby.CQ_HeroSkinPresetSave> CreateCQ_HeroSkinPresetSave(FlatBufferBuilder builder,
      int HeroID = 0,
      byte SlotID = 0,
      StringOffset PresetNameOffset = default(StringOffset)) {
    builder.StartTable(3);
    CQ_HeroSkinPresetSave.AddPresetName(builder, PresetNameOffset);
    CQ_HeroSkinPresetSave.AddHeroID(builder, HeroID);
    CQ_HeroSkinPresetSave.AddSlotID(builder, SlotID);
    return CQ_HeroSkinPresetSave.EndCQ_HeroSkinPresetSave(builder);
  }

  public static void StartCQ_HeroSkinPresetSave(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(0, HeroID, 0); }
  public static void AddSlotID(FlatBufferBuilder builder, byte SlotID) { builder.AddByte(1, SlotID, 0); }
  public static void AddPresetName(FlatBufferBuilder builder, StringOffset PresetNameOffset) { builder.AddOffset(2, PresetNameOffset.Value, 0); }
  public static Offset<Lobby.CQ_HeroSkinPresetSave> EndCQ_HeroSkinPresetSave(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_HeroSkinPresetSave>(o);
  }
  public CQ_HeroSkinPresetSaveT UnPack() {
    var _o = new CQ_HeroSkinPresetSaveT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_HeroSkinPresetSaveT _o) {
    _o.HeroID = this.HeroID;
    _o.SlotID = this.SlotID;
    _o.PresetName = this.PresetName;
  }
  public static Offset<Lobby.CQ_HeroSkinPresetSave> Pack(FlatBufferBuilder builder, CQ_HeroSkinPresetSaveT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_HeroSkinPresetSave>);
    var _PresetName = _o.PresetName == null ? default(StringOffset) : builder.CreateString(_o.PresetName);
    return CreateCQ_HeroSkinPresetSave(
      builder,
      _o.HeroID,
      _o.SlotID,
      _PresetName);
  }
}

public class CQ_HeroSkinPresetSaveT
{
  public int HeroID { get; set; }
  public byte SlotID { get; set; }
  public string PresetName { get; set; }

  public CQ_HeroSkinPresetSaveT() {
    this.HeroID = 0;
    this.SlotID = 0;
    this.PresetName = null;
  }
}


}
