// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_HeroAccessoryChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_HeroAccessoryChange GetRootAsCQ_HeroAccessoryChange(ByteBuffer _bb) { return GetRootAsCQ_HeroAccessoryChange(_bb, new CQ_HeroAccessoryChange()); }
  public static CQ_HeroAccessoryChange GetRootAsCQ_HeroAccessoryChange(ByteBuffer _bb, CQ_HeroAccessoryChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_HeroAccessoryChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.HeroData? ChangeHero { get { int o = __p.__offset(4); return o != 0 ? (Lobby.HeroData?)(new Lobby.HeroData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.CQ_HeroAccessoryChange> CreateCQ_HeroAccessoryChange(FlatBufferBuilder builder,
      Offset<Lobby.HeroData> ChangeHeroOffset = default(Offset<Lobby.HeroData>)) {
    builder.StartTable(1);
    CQ_HeroAccessoryChange.AddChangeHero(builder, ChangeHeroOffset);
    return CQ_HeroAccessoryChange.EndCQ_HeroAccessoryChange(builder);
  }

  public static void StartCQ_HeroAccessoryChange(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddChangeHero(FlatBufferBuilder builder, Offset<Lobby.HeroData> ChangeHeroOffset) { builder.AddOffset(0, ChangeHeroOffset.Value, 0); }
  public static Offset<Lobby.CQ_HeroAccessoryChange> EndCQ_HeroAccessoryChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_HeroAccessoryChange>(o);
  }
  public CQ_HeroAccessoryChangeT UnPack() {
    var _o = new CQ_HeroAccessoryChangeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_HeroAccessoryChangeT _o) {
    _o.ChangeHero = this.ChangeHero.HasValue ? this.ChangeHero.Value.UnPack() : null;
  }
  public static Offset<Lobby.CQ_HeroAccessoryChange> Pack(FlatBufferBuilder builder, CQ_HeroAccessoryChangeT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_HeroAccessoryChange>);
    var _ChangeHero = _o.ChangeHero == null ? default(Offset<Lobby.HeroData>) : Lobby.HeroData.Pack(builder, _o.ChangeHero);
    return CreateCQ_HeroAccessoryChange(
      builder,
      _ChangeHero);
  }
}

public class CQ_HeroAccessoryChangeT
{
  public Lobby.HeroDataT ChangeHero { get; set; }

  public CQ_HeroAccessoryChangeT() {
    this.ChangeHero = null;
  }
}


}
