// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_MazeRewardBoxOpen : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_MazeRewardBoxOpen GetRootAsCQ_MazeRewardBoxOpen(ByteBuffer _bb) { return GetRootAsCQ_MazeRewardBoxOpen(_bb, new CQ_MazeRewardBoxOpen()); }
  public static CQ_MazeRewardBoxOpen GetRootAsCQ_MazeRewardBoxOpen(ByteBuffer _bb, CQ_MazeRewardBoxOpen obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_MazeRewardBoxOpen __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte SlotID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public int BoxID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_MazeRewardBoxOpen> CreateCQ_MazeRewardBoxOpen(FlatBufferBuilder builder,
      byte SlotID = 0,
      int BoxID = 0) {
    builder.StartTable(2);
    CQ_MazeRewardBoxOpen.AddBoxID(builder, BoxID);
    CQ_MazeRewardBoxOpen.AddSlotID(builder, SlotID);
    return CQ_MazeRewardBoxOpen.EndCQ_MazeRewardBoxOpen(builder);
  }

  public static void StartCQ_MazeRewardBoxOpen(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSlotID(FlatBufferBuilder builder, byte SlotID) { builder.AddByte(0, SlotID, 0); }
  public static void AddBoxID(FlatBufferBuilder builder, int BoxID) { builder.AddInt(1, BoxID, 0); }
  public static Offset<Lobby.CQ_MazeRewardBoxOpen> EndCQ_MazeRewardBoxOpen(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_MazeRewardBoxOpen>(o);
  }
  public CQ_MazeRewardBoxOpenT UnPack() {
    var _o = new CQ_MazeRewardBoxOpenT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_MazeRewardBoxOpenT _o) {
    _o.SlotID = this.SlotID;
    _o.BoxID = this.BoxID;
  }
  public static Offset<Lobby.CQ_MazeRewardBoxOpen> Pack(FlatBufferBuilder builder, CQ_MazeRewardBoxOpenT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_MazeRewardBoxOpen>);
    return CreateCQ_MazeRewardBoxOpen(
      builder,
      _o.SlotID,
      _o.BoxID);
  }
}

public class CQ_MazeRewardBoxOpenT
{
  public byte SlotID { get; set; }
  public int BoxID { get; set; }

  public CQ_MazeRewardBoxOpenT() {
    this.SlotID = 0;
    this.BoxID = 0;
  }
}


}
