// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_MailList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_MailList GetRootAsCQ_MailList(ByteBuffer _bb) { return GetRootAsCQ_MailList(_bb, new CQ_MailList()); }
  public static CQ_MailList GetRootAsCQ_MailList(ByteBuffer _bb, CQ_MailList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_MailList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool IsBM { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Lobby.CQ_MailList> CreateCQ_MailList(FlatBufferBuilder builder,
      bool IsBM = false) {
    builder.StartTable(1);
    CQ_MailList.AddIsBM(builder, IsBM);
    return CQ_MailList.EndCQ_MailList(builder);
  }

  public static void StartCQ_MailList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIsBM(FlatBufferBuilder builder, bool IsBM) { builder.AddBool(0, IsBM, false); }
  public static Offset<Lobby.CQ_MailList> EndCQ_MailList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_MailList>(o);
  }
  public CQ_MailListT UnPack() {
    var _o = new CQ_MailListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_MailListT _o) {
    _o.IsBM = this.IsBM;
  }
  public static Offset<Lobby.CQ_MailList> Pack(FlatBufferBuilder builder, CQ_MailListT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_MailList>);
    return CreateCQ_MailList(
      builder,
      _o.IsBM);
  }
}

public class CQ_MailListT
{
  public bool IsBM { get; set; }

  public CQ_MailListT() {
    this.IsBM = false;
  }
}


}
