// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_OpenWorldPositionChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_OpenWorldPositionChange GetRootAsCQ_OpenWorldPositionChange(ByteBuffer _bb) { return GetRootAsCQ_OpenWorldPositionChange(_bb, new CQ_OpenWorldPositionChange()); }
  public static CQ_OpenWorldPositionChange GetRootAsCQ_OpenWorldPositionChange(ByteBuffer _bb, CQ_OpenWorldPositionChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_OpenWorldPositionChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_OpenWorldPositionChange> CreateCQ_OpenWorldPositionChange(FlatBufferBuilder builder,
      int X = 0,
      int Y = 0) {
    builder.StartTable(2);
    CQ_OpenWorldPositionChange.AddY(builder, Y);
    CQ_OpenWorldPositionChange.AddX(builder, X);
    return CQ_OpenWorldPositionChange.EndCQ_OpenWorldPositionChange(builder);
  }

  public static void StartCQ_OpenWorldPositionChange(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddX(FlatBufferBuilder builder, int X) { builder.AddInt(0, X, 0); }
  public static void AddY(FlatBufferBuilder builder, int Y) { builder.AddInt(1, Y, 0); }
  public static Offset<Lobby.CQ_OpenWorldPositionChange> EndCQ_OpenWorldPositionChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_OpenWorldPositionChange>(o);
  }
  public CQ_OpenWorldPositionChangeT UnPack() {
    var _o = new CQ_OpenWorldPositionChangeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_OpenWorldPositionChangeT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
  }
  public static Offset<Lobby.CQ_OpenWorldPositionChange> Pack(FlatBufferBuilder builder, CQ_OpenWorldPositionChangeT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_OpenWorldPositionChange>);
    return CreateCQ_OpenWorldPositionChange(
      builder,
      _o.X,
      _o.Y);
  }
}

public class CQ_OpenWorldPositionChangeT
{
  public int X { get; set; }
  public int Y { get; set; }

  public CQ_OpenWorldPositionChangeT() {
    this.X = 0;
    this.Y = 0;
  }
}


}
