// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_OpenWorldZoneChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_OpenWorldZoneChange GetRootAsCQ_OpenWorldZoneChange(ByteBuffer _bb) { return GetRootAsCQ_OpenWorldZoneChange(_bb, new CQ_OpenWorldZoneChange()); }
  public static CQ_OpenWorldZoneChange GetRootAsCQ_OpenWorldZoneChange(ByteBuffer _bb, CQ_OpenWorldZoneChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_OpenWorldZoneChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ZoneID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_OpenWorldZoneChange> CreateCQ_OpenWorldZoneChange(FlatBufferBuilder builder,
      int ZoneID = 0) {
    builder.StartTable(1);
    CQ_OpenWorldZoneChange.AddZoneID(builder, ZoneID);
    return CQ_OpenWorldZoneChange.EndCQ_OpenWorldZoneChange(builder);
  }

  public static void StartCQ_OpenWorldZoneChange(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddZoneID(FlatBufferBuilder builder, int ZoneID) { builder.AddInt(0, ZoneID, 0); }
  public static Offset<Lobby.CQ_OpenWorldZoneChange> EndCQ_OpenWorldZoneChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_OpenWorldZoneChange>(o);
  }
  public CQ_OpenWorldZoneChangeT UnPack() {
    var _o = new CQ_OpenWorldZoneChangeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_OpenWorldZoneChangeT _o) {
    _o.ZoneID = this.ZoneID;
  }
  public static Offset<Lobby.CQ_OpenWorldZoneChange> Pack(FlatBufferBuilder builder, CQ_OpenWorldZoneChangeT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_OpenWorldZoneChange>);
    return CreateCQ_OpenWorldZoneChange(
      builder,
      _o.ZoneID);
  }
}

public class CQ_OpenWorldZoneChangeT
{
  public int ZoneID { get; set; }

  public CQ_OpenWorldZoneChangeT() {
    this.ZoneID = 0;
  }
}


}
