// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_PenaltyListOther : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_PenaltyListOther GetRootAsCQ_PenaltyListOther(ByteBuffer _bb) { return GetRootAsCQ_PenaltyListOther(_bb, new CQ_PenaltyListOther()); }
  public static CQ_PenaltyListOther GetRootAsCQ_PenaltyListOther(ByteBuffer _bb, CQ_PenaltyListOther obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_PenaltyListOther __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TargetUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_PenaltyListOther> CreateCQ_PenaltyListOther(FlatBufferBuilder builder,
      int TargetUID = 0) {
    builder.StartTable(1);
    CQ_PenaltyListOther.AddTargetUID(builder, TargetUID);
    return CQ_PenaltyListOther.EndCQ_PenaltyListOther(builder);
  }

  public static void StartCQ_PenaltyListOther(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTargetUID(FlatBufferBuilder builder, int TargetUID) { builder.AddInt(0, TargetUID, 0); }
  public static Offset<Lobby.CQ_PenaltyListOther> EndCQ_PenaltyListOther(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_PenaltyListOther>(o);
  }
  public CQ_PenaltyListOtherT UnPack() {
    var _o = new CQ_PenaltyListOtherT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_PenaltyListOtherT _o) {
    _o.TargetUID = this.TargetUID;
  }
  public static Offset<Lobby.CQ_PenaltyListOther> Pack(FlatBufferBuilder builder, CQ_PenaltyListOtherT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_PenaltyListOther>);
    return CreateCQ_PenaltyListOther(
      builder,
      _o.TargetUID);
  }
}

public class CQ_PenaltyListOtherT
{
  public int TargetUID { get; set; }

  public CQ_PenaltyListOtherT() {
    this.TargetUID = 0;
  }
}


}
