// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_RpgRoomStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_RpgRoomStart GetRootAsCQ_RpgRoomStart(ByteBuffer _bb) { return GetRootAsCQ_RpgRoomStart(_bb, new CQ_RpgRoomStart()); }
  public static CQ_RpgRoomStart GetRootAsCQ_RpgRoomStart(ByteBuffer _bb, CQ_RpgRoomStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_RpgRoomStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int LevelID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_RpgRoomStart> CreateCQ_RpgRoomStart(FlatBufferBuilder builder,
      int LevelID = 0) {
    builder.StartTable(1);
    CQ_RpgRoomStart.AddLevelID(builder, LevelID);
    return CQ_RpgRoomStart.EndCQ_RpgRoomStart(builder);
  }

  public static void StartCQ_RpgRoomStart(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLevelID(FlatBufferBuilder builder, int LevelID) { builder.AddInt(0, LevelID, 0); }
  public static Offset<Lobby.CQ_RpgRoomStart> EndCQ_RpgRoomStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_RpgRoomStart>(o);
  }
  public CQ_RpgRoomStartT UnPack() {
    var _o = new CQ_RpgRoomStartT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_RpgRoomStartT _o) {
    _o.LevelID = this.LevelID;
  }
  public static Offset<Lobby.CQ_RpgRoomStart> Pack(FlatBufferBuilder builder, CQ_RpgRoomStartT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_RpgRoomStart>);
    return CreateCQ_RpgRoomStart(
      builder,
      _o.LevelID);
  }
}

public class CQ_RpgRoomStartT
{
  public int LevelID { get; set; }

  public CQ_RpgRoomStartT() {
    this.LevelID = 0;
  }
}


}
