// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_TreasureBoxDaily : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_TreasureBoxDaily GetRootAsCQ_TreasureBoxDaily(ByteBuffer _bb) { return GetRootAsCQ_TreasureBoxDaily(_bb, new CQ_TreasureBoxDaily()); }
  public static CQ_TreasureBoxDaily GetRootAsCQ_TreasureBoxDaily(ByteBuffer _bb, CQ_TreasureBoxDaily obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_TreasureBoxDaily __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCQ_TreasureBoxDaily(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.CQ_TreasureBoxDaily> EndCQ_TreasureBoxDaily(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_TreasureBoxDaily>(o);
  }
  public CQ_TreasureBoxDailyT UnPack() {
    var _o = new CQ_TreasureBoxDailyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_TreasureBoxDailyT _o) {
  }
  public static Offset<Lobby.CQ_TreasureBoxDaily> Pack(FlatBufferBuilder builder, CQ_TreasureBoxDailyT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_TreasureBoxDaily>);
    StartCQ_TreasureBoxDaily(builder);
    return EndCQ_TreasureBoxDaily(builder);
  }
}

public class CQ_TreasureBoxDailyT
{

  public CQ_TreasureBoxDailyT() {
  }
}


}
