// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_UserAccountOther : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_UserAccountOther GetRootAsCQ_UserAccountOther(ByteBuffer _bb) { return GetRootAsCQ_UserAccountOther(_bb, new CQ_UserAccountOther()); }
  public static CQ_UserAccountOther GetRootAsCQ_UserAccountOther(ByteBuffer _bb, CQ_UserAccountOther obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_UserAccountOther __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TargetUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.CQ_UserAccountOther> CreateCQ_UserAccountOther(FlatBufferBuilder builder,
      int TargetUID = 0) {
    builder.StartTable(1);
    CQ_UserAccountOther.AddTargetUID(builder, TargetUID);
    return CQ_UserAccountOther.EndCQ_UserAccountOther(builder);
  }

  public static void StartCQ_UserAccountOther(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTargetUID(FlatBufferBuilder builder, int TargetUID) { builder.AddInt(0, TargetUID, 0); }
  public static Offset<Lobby.CQ_UserAccountOther> EndCQ_UserAccountOther(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_UserAccountOther>(o);
  }
  public CQ_UserAccountOtherT UnPack() {
    var _o = new CQ_UserAccountOtherT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_UserAccountOtherT _o) {
    _o.TargetUID = this.TargetUID;
  }
  public static Offset<Lobby.CQ_UserAccountOther> Pack(FlatBufferBuilder builder, CQ_UserAccountOtherT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_UserAccountOther>);
    return CreateCQ_UserAccountOther(
      builder,
      _o.TargetUID);
  }
}

public class CQ_UserAccountOtherT
{
  public int TargetUID { get; set; }

  public CQ_UserAccountOtherT() {
    this.TargetUID = 0;
  }
}


}
