// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CQ_WonderCubeDelete : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static CQ_WonderCubeDelete GetRootAsCQ_WonderCubeDelete(ByteBuffer _bb) { return GetRootAsCQ_WonderCubeDelete(_bb, new CQ_WonderCubeDelete()); }
  public static CQ_WonderCubeDelete GetRootAsCQ_WonderCubeDelete(ByteBuffer _bb, CQ_WonderCubeDelete obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CQ_WonderCubeDelete __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte SlotID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<Lobby.CQ_WonderCubeDelete> CreateCQ_WonderCubeDelete(FlatBufferBuilder builder,
      byte SlotID = 0) {
    builder.StartTable(1);
    CQ_WonderCubeDelete.AddSlotID(builder, SlotID);
    return CQ_WonderCubeDelete.EndCQ_WonderCubeDelete(builder);
  }

  public static void StartCQ_WonderCubeDelete(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSlotID(FlatBufferBuilder builder, byte SlotID) { builder.AddByte(0, SlotID, 0); }
  public static Offset<Lobby.CQ_WonderCubeDelete> EndCQ_WonderCubeDelete(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.CQ_WonderCubeDelete>(o);
  }
  public CQ_WonderCubeDeleteT UnPack() {
    var _o = new CQ_WonderCubeDeleteT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CQ_WonderCubeDeleteT _o) {
    _o.SlotID = this.SlotID;
  }
  public static Offset<Lobby.CQ_WonderCubeDelete> Pack(FlatBufferBuilder builder, CQ_WonderCubeDeleteT _o) {
    if (_o == null) return default(Offset<Lobby.CQ_WonderCubeDelete>);
    return CreateCQ_WonderCubeDelete(
      builder,
      _o.SlotID);
  }
}

public class CQ_WonderCubeDeleteT
{
  public byte SlotID { get; set; }

  public CQ_WonderCubeDeleteT() {
    this.SlotID = 0;
  }
}


}
