// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DataChipStore : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public DataChipStore __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int StoreID { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int HaveCount { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<Lobby.DataChipStore> CreateDataChipStore(FlatBufferBuilder builder, int StoreID, int HaveCount) {
    builder.Prep(4, 8);
    builder.PutInt(HaveCount);
    builder.PutInt(StoreID);
    return new Offset<Lobby.DataChipStore>(builder.Offset);
  }
  public DataChipStoreT UnPack() {
    var _o = new DataChipStoreT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DataChipStoreT _o) {
    _o.StoreID = this.StoreID;
    _o.HaveCount = this.HaveCount;
  }
  public static Offset<Lobby.DataChipStore> Pack(FlatBufferBuilder builder, DataChipStoreT _o) {
    if (_o == null) return default(Offset<Lobby.DataChipStore>);
    return CreateDataChipStore(
      builder,
      _o.StoreID,
      _o.HaveCount);
  }
}

public class DataChipStoreT
{
  public int StoreID { get; set; }
  public int HaveCount { get; set; }

  public DataChipStoreT() {
    this.StoreID = 0;
    this.HaveCount = 0;
  }
}


}
