// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DediToLobby_WaitRoomFinish_Req : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static DediToLobby_WaitRoomFinish_Req GetRootAsDediToLobby_WaitRoomFinish_Req(ByteBuffer _bb) { return GetRootAsDediToLobby_WaitRoomFinish_Req(_bb, new DediToLobby_WaitRoomFinish_Req()); }
  public static DediToLobby_WaitRoomFinish_Req GetRootAsDediToLobby_WaitRoomFinish_Req(ByteBuffer _bb, DediToLobby_WaitRoomFinish_Req obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DediToLobby_WaitRoomFinish_Req __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Destination { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDestinationBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDestinationBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDestinationArray() { return __p.__vector_as_array<byte>(4); }
  public Lobby.EContentsType ContentsType { get { int o = __p.__offset(6); return o != 0 ? (Lobby.EContentsType)__p.bb.Get(o + __p.bb_pos) : Lobby.EContentsType.None; } }
  public string MatchID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMatchIDBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMatchIDBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMatchIDArray() { return __p.__vector_as_array<byte>(8); }
  public int UID { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int HeroID { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public byte HeroSkinPresetSlotID { get { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte ArtifactDeckSlotID { get { int o = __p.__offset(16); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public long PetUniqueID { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Lobby.DediToLobby_WaitRoomFinish_Req> CreateDediToLobby_WaitRoomFinish_Req(FlatBufferBuilder builder,
      StringOffset DestinationOffset = default(StringOffset),
      Lobby.EContentsType ContentsType = Lobby.EContentsType.None,
      StringOffset MatchIDOffset = default(StringOffset),
      int UID = 0,
      int HeroID = 0,
      byte HeroSkinPresetSlotID = 0,
      byte ArtifactDeckSlotID = 0,
      long PetUniqueID = 0) {
    builder.StartTable(8);
    DediToLobby_WaitRoomFinish_Req.AddPetUniqueID(builder, PetUniqueID);
    DediToLobby_WaitRoomFinish_Req.AddHeroID(builder, HeroID);
    DediToLobby_WaitRoomFinish_Req.AddUID(builder, UID);
    DediToLobby_WaitRoomFinish_Req.AddMatchID(builder, MatchIDOffset);
    DediToLobby_WaitRoomFinish_Req.AddDestination(builder, DestinationOffset);
    DediToLobby_WaitRoomFinish_Req.AddArtifactDeckSlotID(builder, ArtifactDeckSlotID);
    DediToLobby_WaitRoomFinish_Req.AddHeroSkinPresetSlotID(builder, HeroSkinPresetSlotID);
    DediToLobby_WaitRoomFinish_Req.AddContentsType(builder, ContentsType);
    return DediToLobby_WaitRoomFinish_Req.EndDediToLobby_WaitRoomFinish_Req(builder);
  }

  public static void StartDediToLobby_WaitRoomFinish_Req(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddDestination(FlatBufferBuilder builder, StringOffset DestinationOffset) { builder.AddOffset(0, DestinationOffset.Value, 0); }
  public static void AddContentsType(FlatBufferBuilder builder, Lobby.EContentsType ContentsType) { builder.AddByte(1, (byte)ContentsType, 0); }
  public static void AddMatchID(FlatBufferBuilder builder, StringOffset MatchIDOffset) { builder.AddOffset(2, MatchIDOffset.Value, 0); }
  public static void AddUID(FlatBufferBuilder builder, int UID) { builder.AddInt(3, UID, 0); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(4, HeroID, 0); }
  public static void AddHeroSkinPresetSlotID(FlatBufferBuilder builder, byte HeroSkinPresetSlotID) { builder.AddByte(5, HeroSkinPresetSlotID, 0); }
  public static void AddArtifactDeckSlotID(FlatBufferBuilder builder, byte ArtifactDeckSlotID) { builder.AddByte(6, ArtifactDeckSlotID, 0); }
  public static void AddPetUniqueID(FlatBufferBuilder builder, long PetUniqueID) { builder.AddLong(7, PetUniqueID, 0); }
  public static Offset<Lobby.DediToLobby_WaitRoomFinish_Req> EndDediToLobby_WaitRoomFinish_Req(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.DediToLobby_WaitRoomFinish_Req>(o);
  }
  public DediToLobby_WaitRoomFinish_ReqT UnPack() {
    var _o = new DediToLobby_WaitRoomFinish_ReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DediToLobby_WaitRoomFinish_ReqT _o) {
    _o.Destination = this.Destination;
    _o.ContentsType = this.ContentsType;
    _o.MatchID = this.MatchID;
    _o.UID = this.UID;
    _o.HeroID = this.HeroID;
    _o.HeroSkinPresetSlotID = this.HeroSkinPresetSlotID;
    _o.ArtifactDeckSlotID = this.ArtifactDeckSlotID;
    _o.PetUniqueID = this.PetUniqueID;
  }
  public static Offset<Lobby.DediToLobby_WaitRoomFinish_Req> Pack(FlatBufferBuilder builder, DediToLobby_WaitRoomFinish_ReqT _o) {
    if (_o == null) return default(Offset<Lobby.DediToLobby_WaitRoomFinish_Req>);
    var _Destination = _o.Destination == null ? default(StringOffset) : builder.CreateString(_o.Destination);
    var _MatchID = _o.MatchID == null ? default(StringOffset) : builder.CreateString(_o.MatchID);
    return CreateDediToLobby_WaitRoomFinish_Req(
      builder,
      _Destination,
      _o.ContentsType,
      _MatchID,
      _o.UID,
      _o.HeroID,
      _o.HeroSkinPresetSlotID,
      _o.ArtifactDeckSlotID,
      _o.PetUniqueID);
  }
}

public class DediToLobby_WaitRoomFinish_ReqT
{
  public string Destination { get; set; }
  public Lobby.EContentsType ContentsType { get; set; }
  public string MatchID { get; set; }
  public int UID { get; set; }
  public int HeroID { get; set; }
  public byte HeroSkinPresetSlotID { get; set; }
  public byte ArtifactDeckSlotID { get; set; }
  public long PetUniqueID { get; set; }

  public DediToLobby_WaitRoomFinish_ReqT() {
    this.Destination = null;
    this.ContentsType = Lobby.EContentsType.None;
    this.MatchID = null;
    this.UID = 0;
    this.HeroID = 0;
    this.HeroSkinPresetSlotID = 0;
    this.ArtifactDeckSlotID = 0;
    this.PetUniqueID = 0;
  }
}


}
