// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DediToLobby_OpenWorldTime : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static DediToLobby_OpenWorldTime GetRootAsDediToLobby_OpenWorldTime(ByteBuffer _bb) { return GetRootAsDediToLobby_OpenWorldTime(_bb, new DediToLobby_OpenWorldTime()); }
  public static DediToLobby_OpenWorldTime GetRootAsDediToLobby_OpenWorldTime(ByteBuffer _bb, DediToLobby_OpenWorldTime obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DediToLobby_OpenWorldTime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Destination { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDestinationBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDestinationBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDestinationArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Lobby.DediToLobby_OpenWorldTime> CreateDediToLobby_OpenWorldTime(FlatBufferBuilder builder,
      StringOffset DestinationOffset = default(StringOffset)) {
    builder.StartTable(1);
    DediToLobby_OpenWorldTime.AddDestination(builder, DestinationOffset);
    return DediToLobby_OpenWorldTime.EndDediToLobby_OpenWorldTime(builder);
  }

  public static void StartDediToLobby_OpenWorldTime(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDestination(FlatBufferBuilder builder, StringOffset DestinationOffset) { builder.AddOffset(0, DestinationOffset.Value, 0); }
  public static Offset<Lobby.DediToLobby_OpenWorldTime> EndDediToLobby_OpenWorldTime(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.DediToLobby_OpenWorldTime>(o);
  }
  public DediToLobby_OpenWorldTimeT UnPack() {
    var _o = new DediToLobby_OpenWorldTimeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DediToLobby_OpenWorldTimeT _o) {
    _o.Destination = this.Destination;
  }
  public static Offset<Lobby.DediToLobby_OpenWorldTime> Pack(FlatBufferBuilder builder, DediToLobby_OpenWorldTimeT _o) {
    if (_o == null) return default(Offset<Lobby.DediToLobby_OpenWorldTime>);
    var _Destination = _o.Destination == null ? default(StringOffset) : builder.CreateString(_o.Destination);
    return CreateDediToLobby_OpenWorldTime(
      builder,
      _Destination);
  }
}

public class DediToLobby_OpenWorldTimeT
{
  public string Destination { get; set; }

  public DediToLobby_OpenWorldTimeT() {
    this.Destination = null;
  }
}


}
