// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DediToLobby_GoldClashStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static DediToLobby_GoldClashStart GetRootAsDediToLobby_GoldClashStart(ByteBuffer _bb) { return GetRootAsDediToLobby_GoldClashStart(_bb, new DediToLobby_GoldClashStart()); }
  public static DediToLobby_GoldClashStart GetRootAsDediToLobby_GoldClashStart(ByteBuffer _bb, DediToLobby_GoldClashStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DediToLobby_GoldClashStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string DedicatedID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDedicatedIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDedicatedIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDedicatedIDArray() { return __p.__vector_as_array<byte>(4); }
  public Lobby.GoldClashStartInfo? StartInfo { get { int o = __p.__offset(6); return o != 0 ? (Lobby.GoldClashStartInfo?)(new Lobby.GoldClashStartInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.DediToLobby_GoldClashStart> CreateDediToLobby_GoldClashStart(FlatBufferBuilder builder,
      StringOffset DedicatedIDOffset = default(StringOffset),
      Offset<Lobby.GoldClashStartInfo> StartInfoOffset = default(Offset<Lobby.GoldClashStartInfo>)) {
    builder.StartTable(2);
    DediToLobby_GoldClashStart.AddStartInfo(builder, StartInfoOffset);
    DediToLobby_GoldClashStart.AddDedicatedID(builder, DedicatedIDOffset);
    return DediToLobby_GoldClashStart.EndDediToLobby_GoldClashStart(builder);
  }

  public static void StartDediToLobby_GoldClashStart(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDedicatedID(FlatBufferBuilder builder, StringOffset DedicatedIDOffset) { builder.AddOffset(0, DedicatedIDOffset.Value, 0); }
  public static void AddStartInfo(FlatBufferBuilder builder, Offset<Lobby.GoldClashStartInfo> StartInfoOffset) { builder.AddOffset(1, StartInfoOffset.Value, 0); }
  public static Offset<Lobby.DediToLobby_GoldClashStart> EndDediToLobby_GoldClashStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.DediToLobby_GoldClashStart>(o);
  }
  public DediToLobby_GoldClashStartT UnPack() {
    var _o = new DediToLobby_GoldClashStartT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DediToLobby_GoldClashStartT _o) {
    _o.DedicatedID = this.DedicatedID;
    _o.StartInfo = this.StartInfo.HasValue ? this.StartInfo.Value.UnPack() : null;
  }
  public static Offset<Lobby.DediToLobby_GoldClashStart> Pack(FlatBufferBuilder builder, DediToLobby_GoldClashStartT _o) {
    if (_o == null) return default(Offset<Lobby.DediToLobby_GoldClashStart>);
    var _DedicatedID = _o.DedicatedID == null ? default(StringOffset) : builder.CreateString(_o.DedicatedID);
    var _StartInfo = _o.StartInfo == null ? default(Offset<Lobby.GoldClashStartInfo>) : Lobby.GoldClashStartInfo.Pack(builder, _o.StartInfo);
    return CreateDediToLobby_GoldClashStart(
      builder,
      _DedicatedID,
      _StartInfo);
  }
}

public class DediToLobby_GoldClashStartT
{
  public string DedicatedID { get; set; }
  public Lobby.GoldClashStartInfoT StartInfo { get; set; }

  public DediToLobby_GoldClashStartT() {
    this.DedicatedID = null;
    this.StartInfo = null;
  }
}


}
