// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DediToLobby_GoldClashFinish : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static DediToLobby_GoldClashFinish GetRootAsDediToLobby_GoldClashFinish(ByteBuffer _bb) { return GetRootAsDediToLobby_GoldClashFinish(_bb, new DediToLobby_GoldClashFinish()); }
  public static DediToLobby_GoldClashFinish GetRootAsDediToLobby_GoldClashFinish(ByteBuffer _bb, DediToLobby_GoldClashFinish obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DediToLobby_GoldClashFinish __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string DedicatedID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDedicatedIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDedicatedIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDedicatedIDArray() { return __p.__vector_as_array<byte>(4); }
  public Lobby.GoldClashFinishInfo? FinishInfo { get { int o = __p.__offset(6); return o != 0 ? (Lobby.GoldClashFinishInfo?)(new Lobby.GoldClashFinishInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string MatchID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMatchIDBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMatchIDBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMatchIDArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<Lobby.DediToLobby_GoldClashFinish> CreateDediToLobby_GoldClashFinish(FlatBufferBuilder builder,
      StringOffset DedicatedIDOffset = default(StringOffset),
      Offset<Lobby.GoldClashFinishInfo> FinishInfoOffset = default(Offset<Lobby.GoldClashFinishInfo>),
      StringOffset MatchIDOffset = default(StringOffset)) {
    builder.StartTable(3);
    DediToLobby_GoldClashFinish.AddMatchID(builder, MatchIDOffset);
    DediToLobby_GoldClashFinish.AddFinishInfo(builder, FinishInfoOffset);
    DediToLobby_GoldClashFinish.AddDedicatedID(builder, DedicatedIDOffset);
    return DediToLobby_GoldClashFinish.EndDediToLobby_GoldClashFinish(builder);
  }

  public static void StartDediToLobby_GoldClashFinish(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddDedicatedID(FlatBufferBuilder builder, StringOffset DedicatedIDOffset) { builder.AddOffset(0, DedicatedIDOffset.Value, 0); }
  public static void AddFinishInfo(FlatBufferBuilder builder, Offset<Lobby.GoldClashFinishInfo> FinishInfoOffset) { builder.AddOffset(1, FinishInfoOffset.Value, 0); }
  public static void AddMatchID(FlatBufferBuilder builder, StringOffset MatchIDOffset) { builder.AddOffset(2, MatchIDOffset.Value, 0); }
  public static Offset<Lobby.DediToLobby_GoldClashFinish> EndDediToLobby_GoldClashFinish(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.DediToLobby_GoldClashFinish>(o);
  }
  public DediToLobby_GoldClashFinishT UnPack() {
    var _o = new DediToLobby_GoldClashFinishT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DediToLobby_GoldClashFinishT _o) {
    _o.DedicatedID = this.DedicatedID;
    _o.FinishInfo = this.FinishInfo.HasValue ? this.FinishInfo.Value.UnPack() : null;
    _o.MatchID = this.MatchID;
  }
  public static Offset<Lobby.DediToLobby_GoldClashFinish> Pack(FlatBufferBuilder builder, DediToLobby_GoldClashFinishT _o) {
    if (_o == null) return default(Offset<Lobby.DediToLobby_GoldClashFinish>);
    var _DedicatedID = _o.DedicatedID == null ? default(StringOffset) : builder.CreateString(_o.DedicatedID);
    var _FinishInfo = _o.FinishInfo == null ? default(Offset<Lobby.GoldClashFinishInfo>) : Lobby.GoldClashFinishInfo.Pack(builder, _o.FinishInfo);
    var _MatchID = _o.MatchID == null ? default(StringOffset) : builder.CreateString(_o.MatchID);
    return CreateDediToLobby_GoldClashFinish(
      builder,
      _DedicatedID,
      _FinishInfo,
      _MatchID);
  }
}

public class DediToLobby_GoldClashFinishT
{
  public string DedicatedID { get; set; }
  public Lobby.GoldClashFinishInfoT FinishInfo { get; set; }
  public string MatchID { get; set; }

  public DediToLobby_GoldClashFinishT() {
    this.DedicatedID = null;
    this.FinishInfo = null;
    this.MatchID = null;
  }
}


}
