// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EElementalType : byte
{
  None = 0,
  Fire = 1,
  Water = 2,
  Wind = 3,
  Lightning = 4,
  Earth = 5,
};


}
