// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EGuideMissionCategory : byte
{
  None = 0,
  GoldClash = 1,
  RPG = 2,
  Social = 3,
  ETC = 4,
};


}
