// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EItemBoxType : byte
{
  None = 0,
  Fix = 1,
  Random = 2,
  Choose = 3,
  WonderCube = 4,
};


}
