// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EMailStateType : byte
{
  None = 0,
  Arrived = 1,
  Received = 2,
  Deleted = 3,
};


}
