// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EPenaltyReportState : byte
{
  None = 0,
  Dodge = 1,
  Chat = 2,
  Troll = 3,
  Hack = 4,
  Nickname = 5,
  PretendGM = 6,
};


}
