// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EProfileType : byte
{
  None = 0,
  Icon = 1,
  BG = 2,
};


}
