// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EStoreGoodsType : byte
{
  None = 0,
  Single = 1,
  Package = 2,
  Subscribe = 3,
  SeasonPass = 4,
};


}
