// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

public enum EUncheaterReportType : byte
{
  None = 0,
  Ruby = 1,
  Solomon = 2,
  MacroMouse = 3,
  Tool = 4,
};


}
