// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventStoreData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EventStoreData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int StoreID { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int BuyCount { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int NextResetAt { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public int ExpireAt { get { return __p.bb.GetInt(__p.bb_pos + 12); } }

  public static Offset<Lobby.EventStoreData> CreateEventStoreData(FlatBufferBuilder builder, int StoreID, int BuyCount, int NextResetAt, int ExpireAt) {
    builder.Prep(4, 16);
    builder.PutInt(ExpireAt);
    builder.PutInt(NextResetAt);
    builder.PutInt(BuyCount);
    builder.PutInt(StoreID);
    return new Offset<Lobby.EventStoreData>(builder.Offset);
  }
  public EventStoreDataT UnPack() {
    var _o = new EventStoreDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EventStoreDataT _o) {
    _o.StoreID = this.StoreID;
    _o.BuyCount = this.BuyCount;
    _o.NextResetAt = this.NextResetAt;
    _o.ExpireAt = this.ExpireAt;
  }
  public static Offset<Lobby.EventStoreData> Pack(FlatBufferBuilder builder, EventStoreDataT _o) {
    if (_o == null) return default(Offset<Lobby.EventStoreData>);
    return CreateEventStoreData(
      builder,
      _o.StoreID,
      _o.BuyCount,
      _o.NextResetAt,
      _o.ExpireAt);
  }
}

public class EventStoreDataT
{
  public int StoreID { get; set; }
  public int BuyCount { get; set; }
  public int NextResetAt { get; set; }
  public int ExpireAt { get; set; }

  public EventStoreDataT() {
    this.StoreID = 0;
    this.BuyCount = 0;
    this.NextResetAt = 0;
    this.ExpireAt = 0;
  }
}


}
