// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HeroData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static HeroData GetRootAsHeroData(ByteBuffer _bb) { return GetRootAsHeroData(_bb, new HeroData()); }
  public static HeroData GetRootAsHeroData(ByteBuffer _bb, HeroData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HeroData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int HeroID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BattleLevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BattleExp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardedLevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string LeftEyeHexColor { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLeftEyeHexColorBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetLeftEyeHexColorBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetLeftEyeHexColorArray() { return __p.__vector_as_array<byte>(12); }
  public string RightEyeHexColor { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRightEyeHexColorBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetRightEyeHexColorBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetRightEyeHexColorArray() { return __p.__vector_as_array<byte>(14); }
  public int HairSkinID { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BodySkinID { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int HeadID { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float HeadOffsetX { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadOffsetY { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadOffsetZ { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadOffsetW { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadRotateX { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadRotateY { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HeadRotateZ { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int FaceID { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float FaceOffsetX { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceOffsetY { get { int o = __p.__offset(40); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceOffsetZ { get { int o = __p.__offset(42); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceOffsetW { get { int o = __p.__offset(44); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceRotateX { get { int o = __p.__offset(46); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceRotateY { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float FaceRotateZ { get { int o = __p.__offset(50); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int BackID { get { int o = __p.__offset(52); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float BackOffsetX { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackOffsetY { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackOffsetZ { get { int o = __p.__offset(58); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackOffsetW { get { int o = __p.__offset(60); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackRotateX { get { int o = __p.__offset(62); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackRotateY { get { int o = __p.__offset(64); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BackRotateZ { get { int o = __p.__offset(66); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int PelvisID { get { int o = __p.__offset(68); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float PelvisOffsetX { get { int o = __p.__offset(70); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisOffsetY { get { int o = __p.__offset(72); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisOffsetZ { get { int o = __p.__offset(74); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisOffsetW { get { int o = __p.__offset(76); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisRotateX { get { int o = __p.__offset(78); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisRotateY { get { int o = __p.__offset(80); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PelvisRotateZ { get { int o = __p.__offset(82); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int WeaponID { get { int o = __p.__offset(84); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int WinPoseID { get { int o = __p.__offset(86); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ExpireAt { get { int o = __p.__offset(88); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AddPresetCount { get { int o = __p.__offset(90); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.HeroData> CreateHeroData(FlatBufferBuilder builder,
      int HeroID = 0,
      int BattleLevel = 0,
      int BattleExp = 0,
      int RewardedLevel = 0,
      StringOffset LeftEyeHexColorOffset = default(StringOffset),
      StringOffset RightEyeHexColorOffset = default(StringOffset),
      int HairSkinID = 0,
      int BodySkinID = 0,
      int HeadID = 0,
      float HeadOffsetX = 0.0f,
      float HeadOffsetY = 0.0f,
      float HeadOffsetZ = 0.0f,
      float HeadOffsetW = 0.0f,
      float HeadRotateX = 0.0f,
      float HeadRotateY = 0.0f,
      float HeadRotateZ = 0.0f,
      int FaceID = 0,
      float FaceOffsetX = 0.0f,
      float FaceOffsetY = 0.0f,
      float FaceOffsetZ = 0.0f,
      float FaceOffsetW = 0.0f,
      float FaceRotateX = 0.0f,
      float FaceRotateY = 0.0f,
      float FaceRotateZ = 0.0f,
      int BackID = 0,
      float BackOffsetX = 0.0f,
      float BackOffsetY = 0.0f,
      float BackOffsetZ = 0.0f,
      float BackOffsetW = 0.0f,
      float BackRotateX = 0.0f,
      float BackRotateY = 0.0f,
      float BackRotateZ = 0.0f,
      int PelvisID = 0,
      float PelvisOffsetX = 0.0f,
      float PelvisOffsetY = 0.0f,
      float PelvisOffsetZ = 0.0f,
      float PelvisOffsetW = 0.0f,
      float PelvisRotateX = 0.0f,
      float PelvisRotateY = 0.0f,
      float PelvisRotateZ = 0.0f,
      int WeaponID = 0,
      int WinPoseID = 0,
      int ExpireAt = 0,
      int AddPresetCount = 0) {
    builder.StartTable(44);
    HeroData.AddAddPresetCount(builder, AddPresetCount);
    HeroData.AddExpireAt(builder, ExpireAt);
    HeroData.AddWinPoseID(builder, WinPoseID);
    HeroData.AddWeaponID(builder, WeaponID);
    HeroData.AddPelvisRotateZ(builder, PelvisRotateZ);
    HeroData.AddPelvisRotateY(builder, PelvisRotateY);
    HeroData.AddPelvisRotateX(builder, PelvisRotateX);
    HeroData.AddPelvisOffsetW(builder, PelvisOffsetW);
    HeroData.AddPelvisOffsetZ(builder, PelvisOffsetZ);
    HeroData.AddPelvisOffsetY(builder, PelvisOffsetY);
    HeroData.AddPelvisOffsetX(builder, PelvisOffsetX);
    HeroData.AddPelvisID(builder, PelvisID);
    HeroData.AddBackRotateZ(builder, BackRotateZ);
    HeroData.AddBackRotateY(builder, BackRotateY);
    HeroData.AddBackRotateX(builder, BackRotateX);
    HeroData.AddBackOffsetW(builder, BackOffsetW);
    HeroData.AddBackOffsetZ(builder, BackOffsetZ);
    HeroData.AddBackOffsetY(builder, BackOffsetY);
    HeroData.AddBackOffsetX(builder, BackOffsetX);
    HeroData.AddBackID(builder, BackID);
    HeroData.AddFaceRotateZ(builder, FaceRotateZ);
    HeroData.AddFaceRotateY(builder, FaceRotateY);
    HeroData.AddFaceRotateX(builder, FaceRotateX);
    HeroData.AddFaceOffsetW(builder, FaceOffsetW);
    HeroData.AddFaceOffsetZ(builder, FaceOffsetZ);
    HeroData.AddFaceOffsetY(builder, FaceOffsetY);
    HeroData.AddFaceOffsetX(builder, FaceOffsetX);
    HeroData.AddFaceID(builder, FaceID);
    HeroData.AddHeadRotateZ(builder, HeadRotateZ);
    HeroData.AddHeadRotateY(builder, HeadRotateY);
    HeroData.AddHeadRotateX(builder, HeadRotateX);
    HeroData.AddHeadOffsetW(builder, HeadOffsetW);
    HeroData.AddHeadOffsetZ(builder, HeadOffsetZ);
    HeroData.AddHeadOffsetY(builder, HeadOffsetY);
    HeroData.AddHeadOffsetX(builder, HeadOffsetX);
    HeroData.AddHeadID(builder, HeadID);
    HeroData.AddBodySkinID(builder, BodySkinID);
    HeroData.AddHairSkinID(builder, HairSkinID);
    HeroData.AddRightEyeHexColor(builder, RightEyeHexColorOffset);
    HeroData.AddLeftEyeHexColor(builder, LeftEyeHexColorOffset);
    HeroData.AddRewardedLevel(builder, RewardedLevel);
    HeroData.AddBattleExp(builder, BattleExp);
    HeroData.AddBattleLevel(builder, BattleLevel);
    HeroData.AddHeroID(builder, HeroID);
    return HeroData.EndHeroData(builder);
  }

  public static void StartHeroData(FlatBufferBuilder builder) { builder.StartTable(44); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(0, HeroID, 0); }
  public static void AddBattleLevel(FlatBufferBuilder builder, int BattleLevel) { builder.AddInt(1, BattleLevel, 0); }
  public static void AddBattleExp(FlatBufferBuilder builder, int BattleExp) { builder.AddInt(2, BattleExp, 0); }
  public static void AddRewardedLevel(FlatBufferBuilder builder, int RewardedLevel) { builder.AddInt(3, RewardedLevel, 0); }
  public static void AddLeftEyeHexColor(FlatBufferBuilder builder, StringOffset LeftEyeHexColorOffset) { builder.AddOffset(4, LeftEyeHexColorOffset.Value, 0); }
  public static void AddRightEyeHexColor(FlatBufferBuilder builder, StringOffset RightEyeHexColorOffset) { builder.AddOffset(5, RightEyeHexColorOffset.Value, 0); }
  public static void AddHairSkinID(FlatBufferBuilder builder, int HairSkinID) { builder.AddInt(6, HairSkinID, 0); }
  public static void AddBodySkinID(FlatBufferBuilder builder, int BodySkinID) { builder.AddInt(7, BodySkinID, 0); }
  public static void AddHeadID(FlatBufferBuilder builder, int HeadID) { builder.AddInt(8, HeadID, 0); }
  public static void AddHeadOffsetX(FlatBufferBuilder builder, float HeadOffsetX) { builder.AddFloat(9, HeadOffsetX, 0.0f); }
  public static void AddHeadOffsetY(FlatBufferBuilder builder, float HeadOffsetY) { builder.AddFloat(10, HeadOffsetY, 0.0f); }
  public static void AddHeadOffsetZ(FlatBufferBuilder builder, float HeadOffsetZ) { builder.AddFloat(11, HeadOffsetZ, 0.0f); }
  public static void AddHeadOffsetW(FlatBufferBuilder builder, float HeadOffsetW) { builder.AddFloat(12, HeadOffsetW, 0.0f); }
  public static void AddHeadRotateX(FlatBufferBuilder builder, float HeadRotateX) { builder.AddFloat(13, HeadRotateX, 0.0f); }
  public static void AddHeadRotateY(FlatBufferBuilder builder, float HeadRotateY) { builder.AddFloat(14, HeadRotateY, 0.0f); }
  public static void AddHeadRotateZ(FlatBufferBuilder builder, float HeadRotateZ) { builder.AddFloat(15, HeadRotateZ, 0.0f); }
  public static void AddFaceID(FlatBufferBuilder builder, int FaceID) { builder.AddInt(16, FaceID, 0); }
  public static void AddFaceOffsetX(FlatBufferBuilder builder, float FaceOffsetX) { builder.AddFloat(17, FaceOffsetX, 0.0f); }
  public static void AddFaceOffsetY(FlatBufferBuilder builder, float FaceOffsetY) { builder.AddFloat(18, FaceOffsetY, 0.0f); }
  public static void AddFaceOffsetZ(FlatBufferBuilder builder, float FaceOffsetZ) { builder.AddFloat(19, FaceOffsetZ, 0.0f); }
  public static void AddFaceOffsetW(FlatBufferBuilder builder, float FaceOffsetW) { builder.AddFloat(20, FaceOffsetW, 0.0f); }
  public static void AddFaceRotateX(FlatBufferBuilder builder, float FaceRotateX) { builder.AddFloat(21, FaceRotateX, 0.0f); }
  public static void AddFaceRotateY(FlatBufferBuilder builder, float FaceRotateY) { builder.AddFloat(22, FaceRotateY, 0.0f); }
  public static void AddFaceRotateZ(FlatBufferBuilder builder, float FaceRotateZ) { builder.AddFloat(23, FaceRotateZ, 0.0f); }
  public static void AddBackID(FlatBufferBuilder builder, int BackID) { builder.AddInt(24, BackID, 0); }
  public static void AddBackOffsetX(FlatBufferBuilder builder, float BackOffsetX) { builder.AddFloat(25, BackOffsetX, 0.0f); }
  public static void AddBackOffsetY(FlatBufferBuilder builder, float BackOffsetY) { builder.AddFloat(26, BackOffsetY, 0.0f); }
  public static void AddBackOffsetZ(FlatBufferBuilder builder, float BackOffsetZ) { builder.AddFloat(27, BackOffsetZ, 0.0f); }
  public static void AddBackOffsetW(FlatBufferBuilder builder, float BackOffsetW) { builder.AddFloat(28, BackOffsetW, 0.0f); }
  public static void AddBackRotateX(FlatBufferBuilder builder, float BackRotateX) { builder.AddFloat(29, BackRotateX, 0.0f); }
  public static void AddBackRotateY(FlatBufferBuilder builder, float BackRotateY) { builder.AddFloat(30, BackRotateY, 0.0f); }
  public static void AddBackRotateZ(FlatBufferBuilder builder, float BackRotateZ) { builder.AddFloat(31, BackRotateZ, 0.0f); }
  public static void AddPelvisID(FlatBufferBuilder builder, int PelvisID) { builder.AddInt(32, PelvisID, 0); }
  public static void AddPelvisOffsetX(FlatBufferBuilder builder, float PelvisOffsetX) { builder.AddFloat(33, PelvisOffsetX, 0.0f); }
  public static void AddPelvisOffsetY(FlatBufferBuilder builder, float PelvisOffsetY) { builder.AddFloat(34, PelvisOffsetY, 0.0f); }
  public static void AddPelvisOffsetZ(FlatBufferBuilder builder, float PelvisOffsetZ) { builder.AddFloat(35, PelvisOffsetZ, 0.0f); }
  public static void AddPelvisOffsetW(FlatBufferBuilder builder, float PelvisOffsetW) { builder.AddFloat(36, PelvisOffsetW, 0.0f); }
  public static void AddPelvisRotateX(FlatBufferBuilder builder, float PelvisRotateX) { builder.AddFloat(37, PelvisRotateX, 0.0f); }
  public static void AddPelvisRotateY(FlatBufferBuilder builder, float PelvisRotateY) { builder.AddFloat(38, PelvisRotateY, 0.0f); }
  public static void AddPelvisRotateZ(FlatBufferBuilder builder, float PelvisRotateZ) { builder.AddFloat(39, PelvisRotateZ, 0.0f); }
  public static void AddWeaponID(FlatBufferBuilder builder, int WeaponID) { builder.AddInt(40, WeaponID, 0); }
  public static void AddWinPoseID(FlatBufferBuilder builder, int WinPoseID) { builder.AddInt(41, WinPoseID, 0); }
  public static void AddExpireAt(FlatBufferBuilder builder, int ExpireAt) { builder.AddInt(42, ExpireAt, 0); }
  public static void AddAddPresetCount(FlatBufferBuilder builder, int AddPresetCount) { builder.AddInt(43, AddPresetCount, 0); }
  public static Offset<Lobby.HeroData> EndHeroData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.HeroData>(o);
  }
  public HeroDataT UnPack() {
    var _o = new HeroDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(HeroDataT _o) {
    _o.HeroID = this.HeroID;
    _o.BattleLevel = this.BattleLevel;
    _o.BattleExp = this.BattleExp;
    _o.RewardedLevel = this.RewardedLevel;
    _o.LeftEyeHexColor = this.LeftEyeHexColor;
    _o.RightEyeHexColor = this.RightEyeHexColor;
    _o.HairSkinID = this.HairSkinID;
    _o.BodySkinID = this.BodySkinID;
    _o.HeadID = this.HeadID;
    _o.HeadOffsetX = this.HeadOffsetX;
    _o.HeadOffsetY = this.HeadOffsetY;
    _o.HeadOffsetZ = this.HeadOffsetZ;
    _o.HeadOffsetW = this.HeadOffsetW;
    _o.HeadRotateX = this.HeadRotateX;
    _o.HeadRotateY = this.HeadRotateY;
    _o.HeadRotateZ = this.HeadRotateZ;
    _o.FaceID = this.FaceID;
    _o.FaceOffsetX = this.FaceOffsetX;
    _o.FaceOffsetY = this.FaceOffsetY;
    _o.FaceOffsetZ = this.FaceOffsetZ;
    _o.FaceOffsetW = this.FaceOffsetW;
    _o.FaceRotateX = this.FaceRotateX;
    _o.FaceRotateY = this.FaceRotateY;
    _o.FaceRotateZ = this.FaceRotateZ;
    _o.BackID = this.BackID;
    _o.BackOffsetX = this.BackOffsetX;
    _o.BackOffsetY = this.BackOffsetY;
    _o.BackOffsetZ = this.BackOffsetZ;
    _o.BackOffsetW = this.BackOffsetW;
    _o.BackRotateX = this.BackRotateX;
    _o.BackRotateY = this.BackRotateY;
    _o.BackRotateZ = this.BackRotateZ;
    _o.PelvisID = this.PelvisID;
    _o.PelvisOffsetX = this.PelvisOffsetX;
    _o.PelvisOffsetY = this.PelvisOffsetY;
    _o.PelvisOffsetZ = this.PelvisOffsetZ;
    _o.PelvisOffsetW = this.PelvisOffsetW;
    _o.PelvisRotateX = this.PelvisRotateX;
    _o.PelvisRotateY = this.PelvisRotateY;
    _o.PelvisRotateZ = this.PelvisRotateZ;
    _o.WeaponID = this.WeaponID;
    _o.WinPoseID = this.WinPoseID;
    _o.ExpireAt = this.ExpireAt;
    _o.AddPresetCount = this.AddPresetCount;
  }
  public static Offset<Lobby.HeroData> Pack(FlatBufferBuilder builder, HeroDataT _o) {
    if (_o == null) return default(Offset<Lobby.HeroData>);
    var _LeftEyeHexColor = _o.LeftEyeHexColor == null ? default(StringOffset) : builder.CreateString(_o.LeftEyeHexColor);
    var _RightEyeHexColor = _o.RightEyeHexColor == null ? default(StringOffset) : builder.CreateString(_o.RightEyeHexColor);
    return CreateHeroData(
      builder,
      _o.HeroID,
      _o.BattleLevel,
      _o.BattleExp,
      _o.RewardedLevel,
      _LeftEyeHexColor,
      _RightEyeHexColor,
      _o.HairSkinID,
      _o.BodySkinID,
      _o.HeadID,
      _o.HeadOffsetX,
      _o.HeadOffsetY,
      _o.HeadOffsetZ,
      _o.HeadOffsetW,
      _o.HeadRotateX,
      _o.HeadRotateY,
      _o.HeadRotateZ,
      _o.FaceID,
      _o.FaceOffsetX,
      _o.FaceOffsetY,
      _o.FaceOffsetZ,
      _o.FaceOffsetW,
      _o.FaceRotateX,
      _o.FaceRotateY,
      _o.FaceRotateZ,
      _o.BackID,
      _o.BackOffsetX,
      _o.BackOffsetY,
      _o.BackOffsetZ,
      _o.BackOffsetW,
      _o.BackRotateX,
      _o.BackRotateY,
      _o.BackRotateZ,
      _o.PelvisID,
      _o.PelvisOffsetX,
      _o.PelvisOffsetY,
      _o.PelvisOffsetZ,
      _o.PelvisOffsetW,
      _o.PelvisRotateX,
      _o.PelvisRotateY,
      _o.PelvisRotateZ,
      _o.WeaponID,
      _o.WinPoseID,
      _o.ExpireAt,
      _o.AddPresetCount);
  }
}

public class HeroDataT
{
  public int HeroID { get; set; }
  public int BattleLevel { get; set; }
  public int BattleExp { get; set; }
  public int RewardedLevel { get; set; }
  public string LeftEyeHexColor { get; set; }
  public string RightEyeHexColor { get; set; }
  public int HairSkinID { get; set; }
  public int BodySkinID { get; set; }
  public int HeadID { get; set; }
  public float HeadOffsetX { get; set; }
  public float HeadOffsetY { get; set; }
  public float HeadOffsetZ { get; set; }
  public float HeadOffsetW { get; set; }
  public float HeadRotateX { get; set; }
  public float HeadRotateY { get; set; }
  public float HeadRotateZ { get; set; }
  public int FaceID { get; set; }
  public float FaceOffsetX { get; set; }
  public float FaceOffsetY { get; set; }
  public float FaceOffsetZ { get; set; }
  public float FaceOffsetW { get; set; }
  public float FaceRotateX { get; set; }
  public float FaceRotateY { get; set; }
  public float FaceRotateZ { get; set; }
  public int BackID { get; set; }
  public float BackOffsetX { get; set; }
  public float BackOffsetY { get; set; }
  public float BackOffsetZ { get; set; }
  public float BackOffsetW { get; set; }
  public float BackRotateX { get; set; }
  public float BackRotateY { get; set; }
  public float BackRotateZ { get; set; }
  public int PelvisID { get; set; }
  public float PelvisOffsetX { get; set; }
  public float PelvisOffsetY { get; set; }
  public float PelvisOffsetZ { get; set; }
  public float PelvisOffsetW { get; set; }
  public float PelvisRotateX { get; set; }
  public float PelvisRotateY { get; set; }
  public float PelvisRotateZ { get; set; }
  public int WeaponID { get; set; }
  public int WinPoseID { get; set; }
  public int ExpireAt { get; set; }
  public int AddPresetCount { get; set; }

  public HeroDataT() {
    this.HeroID = 0;
    this.BattleLevel = 0;
    this.BattleExp = 0;
    this.RewardedLevel = 0;
    this.LeftEyeHexColor = null;
    this.RightEyeHexColor = null;
    this.HairSkinID = 0;
    this.BodySkinID = 0;
    this.HeadID = 0;
    this.HeadOffsetX = 0.0f;
    this.HeadOffsetY = 0.0f;
    this.HeadOffsetZ = 0.0f;
    this.HeadOffsetW = 0.0f;
    this.HeadRotateX = 0.0f;
    this.HeadRotateY = 0.0f;
    this.HeadRotateZ = 0.0f;
    this.FaceID = 0;
    this.FaceOffsetX = 0.0f;
    this.FaceOffsetY = 0.0f;
    this.FaceOffsetZ = 0.0f;
    this.FaceOffsetW = 0.0f;
    this.FaceRotateX = 0.0f;
    this.FaceRotateY = 0.0f;
    this.FaceRotateZ = 0.0f;
    this.BackID = 0;
    this.BackOffsetX = 0.0f;
    this.BackOffsetY = 0.0f;
    this.BackOffsetZ = 0.0f;
    this.BackOffsetW = 0.0f;
    this.BackRotateX = 0.0f;
    this.BackRotateY = 0.0f;
    this.BackRotateZ = 0.0f;
    this.PelvisID = 0;
    this.PelvisOffsetX = 0.0f;
    this.PelvisOffsetY = 0.0f;
    this.PelvisOffsetZ = 0.0f;
    this.PelvisOffsetW = 0.0f;
    this.PelvisRotateX = 0.0f;
    this.PelvisRotateY = 0.0f;
    this.PelvisRotateZ = 0.0f;
    this.WeaponID = 0;
    this.WinPoseID = 0;
    this.ExpireAt = 0;
    this.AddPresetCount = 0;
  }
}


}
