// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LobbyToDedi_HeroSkinPresetData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static LobbyToDedi_HeroSkinPresetData GetRootAsLobbyToDedi_HeroSkinPresetData(ByteBuffer _bb) { return GetRootAsLobbyToDedi_HeroSkinPresetData(_bb, new LobbyToDedi_HeroSkinPresetData()); }
  public static LobbyToDedi_HeroSkinPresetData GetRootAsLobbyToDedi_HeroSkinPresetData(ByteBuffer _bb, LobbyToDedi_HeroSkinPresetData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyToDedi_HeroSkinPresetData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int UID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int HeroID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public byte SlotID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public Lobby.HeroSkinPresetSlotData? PresetData { get { int o = __p.__offset(10); return o != 0 ? (Lobby.HeroSkinPresetSlotData?)(new Lobby.HeroSkinPresetSlotData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.LobbyToDedi_HeroSkinPresetData> CreateLobbyToDedi_HeroSkinPresetData(FlatBufferBuilder builder,
      int UID = 0,
      int HeroID = 0,
      byte SlotID = 0,
      Offset<Lobby.HeroSkinPresetSlotData> PresetDataOffset = default(Offset<Lobby.HeroSkinPresetSlotData>)) {
    builder.StartTable(4);
    LobbyToDedi_HeroSkinPresetData.AddPresetData(builder, PresetDataOffset);
    LobbyToDedi_HeroSkinPresetData.AddHeroID(builder, HeroID);
    LobbyToDedi_HeroSkinPresetData.AddUID(builder, UID);
    LobbyToDedi_HeroSkinPresetData.AddSlotID(builder, SlotID);
    return LobbyToDedi_HeroSkinPresetData.EndLobbyToDedi_HeroSkinPresetData(builder);
  }

  public static void StartLobbyToDedi_HeroSkinPresetData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddUID(FlatBufferBuilder builder, int UID) { builder.AddInt(0, UID, 0); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(1, HeroID, 0); }
  public static void AddSlotID(FlatBufferBuilder builder, byte SlotID) { builder.AddByte(2, SlotID, 0); }
  public static void AddPresetData(FlatBufferBuilder builder, Offset<Lobby.HeroSkinPresetSlotData> PresetDataOffset) { builder.AddOffset(3, PresetDataOffset.Value, 0); }
  public static Offset<Lobby.LobbyToDedi_HeroSkinPresetData> EndLobbyToDedi_HeroSkinPresetData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.LobbyToDedi_HeroSkinPresetData>(o);
  }
  public LobbyToDedi_HeroSkinPresetDataT UnPack() {
    var _o = new LobbyToDedi_HeroSkinPresetDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LobbyToDedi_HeroSkinPresetDataT _o) {
    _o.UID = this.UID;
    _o.HeroID = this.HeroID;
    _o.SlotID = this.SlotID;
    _o.PresetData = this.PresetData.HasValue ? this.PresetData.Value.UnPack() : null;
  }
  public static Offset<Lobby.LobbyToDedi_HeroSkinPresetData> Pack(FlatBufferBuilder builder, LobbyToDedi_HeroSkinPresetDataT _o) {
    if (_o == null) return default(Offset<Lobby.LobbyToDedi_HeroSkinPresetData>);
    var _PresetData = _o.PresetData == null ? default(Offset<Lobby.HeroSkinPresetSlotData>) : Lobby.HeroSkinPresetSlotData.Pack(builder, _o.PresetData);
    return CreateLobbyToDedi_HeroSkinPresetData(
      builder,
      _o.UID,
      _o.HeroID,
      _o.SlotID,
      _PresetData);
  }
}

public class LobbyToDedi_HeroSkinPresetDataT
{
  public int UID { get; set; }
  public int HeroID { get; set; }
  public byte SlotID { get; set; }
  public Lobby.HeroSkinPresetSlotDataT PresetData { get; set; }

  public LobbyToDedi_HeroSkinPresetDataT() {
    this.UID = 0;
    this.HeroID = 0;
    this.SlotID = 0;
    this.PresetData = null;
  }
}


}
