// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LobbyToDedi_RaidUserData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static LobbyToDedi_RaidUserData GetRootAsLobbyToDedi_RaidUserData(ByteBuffer _bb) { return GetRootAsLobbyToDedi_RaidUserData(_bb, new LobbyToDedi_RaidUserData()); }
  public static LobbyToDedi_RaidUserData GetRootAsLobbyToDedi_RaidUserData(ByteBuffer _bb, LobbyToDedi_RaidUserData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyToDedi_RaidUserData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int UID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Nick { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNickBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNickBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNickArray() { return __p.__vector_as_array<byte>(6); }
  public string TeamID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTeamIDBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTeamIDBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTeamIDArray() { return __p.__vector_as_array<byte>(8); }
  public Lobby.HeroData? Hero { get { int o = __p.__offset(10); return o != 0 ? (Lobby.HeroData?)(new Lobby.HeroData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Lobby.HeroSkinData? HairSkin { get { int o = __p.__offset(12); return o != 0 ? (Lobby.HeroSkinData?)(new Lobby.HeroSkinData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Lobby.HeroSkinData? BodySkin { get { int o = __p.__offset(14); return o != 0 ? (Lobby.HeroSkinData?)(new Lobby.HeroSkinData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Lobby.ArtifactData? ArtifactList(int j) { int o = __p.__offset(16); return o != 0 ? (Lobby.ArtifactData?)(new Lobby.ArtifactData()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int ArtifactListLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.ArtifactData? DeckArtifactList(int j) { int o = __p.__offset(18); return o != 0 ? (Lobby.ArtifactData?)(new Lobby.ArtifactData()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int DeckArtifactListLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int EntitlementID { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool NotExistsUser { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Lobby.LobbyToDedi_RaidUserData> CreateLobbyToDedi_RaidUserData(FlatBufferBuilder builder,
      int UID = 0,
      StringOffset NickOffset = default(StringOffset),
      StringOffset TeamIDOffset = default(StringOffset),
      Offset<Lobby.HeroData> HeroOffset = default(Offset<Lobby.HeroData>),
      Offset<Lobby.HeroSkinData> HairSkinOffset = default(Offset<Lobby.HeroSkinData>),
      Offset<Lobby.HeroSkinData> BodySkinOffset = default(Offset<Lobby.HeroSkinData>),
      VectorOffset ArtifactListOffset = default(VectorOffset),
      VectorOffset DeckArtifactListOffset = default(VectorOffset),
      int EntitlementID = 0,
      bool NotExistsUser = false) {
    builder.StartTable(10);
    LobbyToDedi_RaidUserData.AddEntitlementID(builder, EntitlementID);
    LobbyToDedi_RaidUserData.AddDeckArtifactList(builder, DeckArtifactListOffset);
    LobbyToDedi_RaidUserData.AddArtifactList(builder, ArtifactListOffset);
    LobbyToDedi_RaidUserData.AddBodySkin(builder, BodySkinOffset);
    LobbyToDedi_RaidUserData.AddHairSkin(builder, HairSkinOffset);
    LobbyToDedi_RaidUserData.AddHero(builder, HeroOffset);
    LobbyToDedi_RaidUserData.AddTeamID(builder, TeamIDOffset);
    LobbyToDedi_RaidUserData.AddNick(builder, NickOffset);
    LobbyToDedi_RaidUserData.AddUID(builder, UID);
    LobbyToDedi_RaidUserData.AddNotExistsUser(builder, NotExistsUser);
    return LobbyToDedi_RaidUserData.EndLobbyToDedi_RaidUserData(builder);
  }

  public static void StartLobbyToDedi_RaidUserData(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddUID(FlatBufferBuilder builder, int UID) { builder.AddInt(0, UID, 0); }
  public static void AddNick(FlatBufferBuilder builder, StringOffset NickOffset) { builder.AddOffset(1, NickOffset.Value, 0); }
  public static void AddTeamID(FlatBufferBuilder builder, StringOffset TeamIDOffset) { builder.AddOffset(2, TeamIDOffset.Value, 0); }
  public static void AddHero(FlatBufferBuilder builder, Offset<Lobby.HeroData> HeroOffset) { builder.AddOffset(3, HeroOffset.Value, 0); }
  public static void AddHairSkin(FlatBufferBuilder builder, Offset<Lobby.HeroSkinData> HairSkinOffset) { builder.AddOffset(4, HairSkinOffset.Value, 0); }
  public static void AddBodySkin(FlatBufferBuilder builder, Offset<Lobby.HeroSkinData> BodySkinOffset) { builder.AddOffset(5, BodySkinOffset.Value, 0); }
  public static void AddArtifactList(FlatBufferBuilder builder, VectorOffset ArtifactListOffset) { builder.AddOffset(6, ArtifactListOffset.Value, 0); }
  public static void StartArtifactListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddDeckArtifactList(FlatBufferBuilder builder, VectorOffset DeckArtifactListOffset) { builder.AddOffset(7, DeckArtifactListOffset.Value, 0); }
  public static void StartDeckArtifactListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddEntitlementID(FlatBufferBuilder builder, int EntitlementID) { builder.AddInt(8, EntitlementID, 0); }
  public static void AddNotExistsUser(FlatBufferBuilder builder, bool NotExistsUser) { builder.AddBool(9, NotExistsUser, false); }
  public static Offset<Lobby.LobbyToDedi_RaidUserData> EndLobbyToDedi_RaidUserData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.LobbyToDedi_RaidUserData>(o);
  }
  public LobbyToDedi_RaidUserDataT UnPack() {
    var _o = new LobbyToDedi_RaidUserDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LobbyToDedi_RaidUserDataT _o) {
    _o.UID = this.UID;
    _o.Nick = this.Nick;
    _o.TeamID = this.TeamID;
    _o.Hero = this.Hero.HasValue ? this.Hero.Value.UnPack() : null;
    _o.HairSkin = this.HairSkin.HasValue ? this.HairSkin.Value.UnPack() : null;
    _o.BodySkin = this.BodySkin.HasValue ? this.BodySkin.Value.UnPack() : null;
    _o.ArtifactList = new List<Lobby.ArtifactDataT>();
    for (var _j = 0; _j < this.ArtifactListLength; ++_j) {_o.ArtifactList.Add(this.ArtifactList(_j).HasValue ? this.ArtifactList(_j).Value.UnPack() : null);}
    _o.DeckArtifactList = new List<Lobby.ArtifactDataT>();
    for (var _j = 0; _j < this.DeckArtifactListLength; ++_j) {_o.DeckArtifactList.Add(this.DeckArtifactList(_j).HasValue ? this.DeckArtifactList(_j).Value.UnPack() : null);}
    _o.EntitlementID = this.EntitlementID;
    _o.NotExistsUser = this.NotExistsUser;
  }
  public static Offset<Lobby.LobbyToDedi_RaidUserData> Pack(FlatBufferBuilder builder, LobbyToDedi_RaidUserDataT _o) {
    if (_o == null) return default(Offset<Lobby.LobbyToDedi_RaidUserData>);
    var _Nick = _o.Nick == null ? default(StringOffset) : builder.CreateString(_o.Nick);
    var _TeamID = _o.TeamID == null ? default(StringOffset) : builder.CreateString(_o.TeamID);
    var _Hero = _o.Hero == null ? default(Offset<Lobby.HeroData>) : Lobby.HeroData.Pack(builder, _o.Hero);
    var _HairSkin = _o.HairSkin == null ? default(Offset<Lobby.HeroSkinData>) : Lobby.HeroSkinData.Pack(builder, _o.HairSkin);
    var _BodySkin = _o.BodySkin == null ? default(Offset<Lobby.HeroSkinData>) : Lobby.HeroSkinData.Pack(builder, _o.BodySkin);
    var _ArtifactList = default(VectorOffset);
    if (_o.ArtifactList != null) {
      StartArtifactListVector(builder, _o.ArtifactList.Count);
      for (var _j = _o.ArtifactList.Count - 1; _j >= 0; --_j) { Lobby.ArtifactData.Pack(builder, _o.ArtifactList[_j]); }
      _ArtifactList = builder.EndVector();
    }
    var _DeckArtifactList = default(VectorOffset);
    if (_o.DeckArtifactList != null) {
      StartDeckArtifactListVector(builder, _o.DeckArtifactList.Count);
      for (var _j = _o.DeckArtifactList.Count - 1; _j >= 0; --_j) { Lobby.ArtifactData.Pack(builder, _o.DeckArtifactList[_j]); }
      _DeckArtifactList = builder.EndVector();
    }
    return CreateLobbyToDedi_RaidUserData(
      builder,
      _o.UID,
      _Nick,
      _TeamID,
      _Hero,
      _HairSkin,
      _BodySkin,
      _ArtifactList,
      _DeckArtifactList,
      _o.EntitlementID,
      _o.NotExistsUser);
  }
}

public class LobbyToDedi_RaidUserDataT
{
  public int UID { get; set; }
  public string Nick { get; set; }
  public string TeamID { get; set; }
  public Lobby.HeroDataT Hero { get; set; }
  public Lobby.HeroSkinDataT HairSkin { get; set; }
  public Lobby.HeroSkinDataT BodySkin { get; set; }
  public List<Lobby.ArtifactDataT> ArtifactList { get; set; }
  public List<Lobby.ArtifactDataT> DeckArtifactList { get; set; }
  public int EntitlementID { get; set; }
  public bool NotExistsUser { get; set; }

  public LobbyToDedi_RaidUserDataT() {
    this.UID = 0;
    this.Nick = null;
    this.TeamID = null;
    this.Hero = null;
    this.HairSkin = null;
    this.BodySkin = null;
    this.ArtifactList = null;
    this.DeckArtifactList = null;
    this.EntitlementID = 0;
    this.NotExistsUser = false;
  }
}


}
