// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LobbyToLobby_CustomGameLeaveToMaster : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static LobbyToLobby_CustomGameLeaveToMaster GetRootAsLobbyToLobby_CustomGameLeaveToMaster(ByteBuffer _bb) { return GetRootAsLobbyToLobby_CustomGameLeaveToMaster(_bb, new LobbyToLobby_CustomGameLeaveToMaster()); }
  public static LobbyToLobby_CustomGameLeaveToMaster GetRootAsLobbyToLobby_CustomGameLeaveToMaster(ByteBuffer _bb, LobbyToLobby_CustomGameLeaveToMaster obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyToLobby_CustomGameLeaveToMaster __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoomID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoomIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRoomIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoomIDArray() { return __p.__vector_as_array<byte>(4); }
  public int LeaveMemberUID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string MasterNick { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMasterNickBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMasterNickBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMasterNickArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<Lobby.LobbyToLobby_CustomGameLeaveToMaster> CreateLobbyToLobby_CustomGameLeaveToMaster(FlatBufferBuilder builder,
      StringOffset RoomIDOffset = default(StringOffset),
      int LeaveMemberUID = 0,
      StringOffset MasterNickOffset = default(StringOffset)) {
    builder.StartTable(3);
    LobbyToLobby_CustomGameLeaveToMaster.AddMasterNick(builder, MasterNickOffset);
    LobbyToLobby_CustomGameLeaveToMaster.AddLeaveMemberUID(builder, LeaveMemberUID);
    LobbyToLobby_CustomGameLeaveToMaster.AddRoomID(builder, RoomIDOffset);
    return LobbyToLobby_CustomGameLeaveToMaster.EndLobbyToLobby_CustomGameLeaveToMaster(builder);
  }

  public static void StartLobbyToLobby_CustomGameLeaveToMaster(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddRoomID(FlatBufferBuilder builder, StringOffset RoomIDOffset) { builder.AddOffset(0, RoomIDOffset.Value, 0); }
  public static void AddLeaveMemberUID(FlatBufferBuilder builder, int LeaveMemberUID) { builder.AddInt(1, LeaveMemberUID, 0); }
  public static void AddMasterNick(FlatBufferBuilder builder, StringOffset MasterNickOffset) { builder.AddOffset(2, MasterNickOffset.Value, 0); }
  public static Offset<Lobby.LobbyToLobby_CustomGameLeaveToMaster> EndLobbyToLobby_CustomGameLeaveToMaster(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.LobbyToLobby_CustomGameLeaveToMaster>(o);
  }
  public LobbyToLobby_CustomGameLeaveToMasterT UnPack() {
    var _o = new LobbyToLobby_CustomGameLeaveToMasterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LobbyToLobby_CustomGameLeaveToMasterT _o) {
    _o.RoomID = this.RoomID;
    _o.LeaveMemberUID = this.LeaveMemberUID;
    _o.MasterNick = this.MasterNick;
  }
  public static Offset<Lobby.LobbyToLobby_CustomGameLeaveToMaster> Pack(FlatBufferBuilder builder, LobbyToLobby_CustomGameLeaveToMasterT _o) {
    if (_o == null) return default(Offset<Lobby.LobbyToLobby_CustomGameLeaveToMaster>);
    var _RoomID = _o.RoomID == null ? default(StringOffset) : builder.CreateString(_o.RoomID);
    var _MasterNick = _o.MasterNick == null ? default(StringOffset) : builder.CreateString(_o.MasterNick);
    return CreateLobbyToLobby_CustomGameLeaveToMaster(
      builder,
      _RoomID,
      _o.LeaveMemberUID,
      _MasterNick);
  }
}

public class LobbyToLobby_CustomGameLeaveToMasterT
{
  public string RoomID { get; set; }
  public int LeaveMemberUID { get; set; }
  public string MasterNick { get; set; }

  public LobbyToLobby_CustomGameLeaveToMasterT() {
    this.RoomID = null;
    this.LeaveMemberUID = 0;
    this.MasterNick = null;
  }
}


}
