// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LobbyErrorData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static LobbyErrorData GetRootAsLobbyErrorData(ByteBuffer _bb) { return GetRootAsLobbyErrorData(_bb, new LobbyErrorData()); }
  public static LobbyErrorData GetRootAsLobbyErrorData(ByteBuffer _bb, LobbyErrorData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyErrorData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Error { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Lobby.LobbyErrorData> CreateLobbyErrorData(FlatBufferBuilder builder,
      StringOffset ErrorOffset = default(StringOffset)) {
    builder.StartTable(1);
    LobbyErrorData.AddError(builder, ErrorOffset);
    return LobbyErrorData.EndLobbyErrorData(builder);
  }

  public static void StartLobbyErrorData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddError(FlatBufferBuilder builder, StringOffset ErrorOffset) { builder.AddOffset(0, ErrorOffset.Value, 0); }
  public static Offset<Lobby.LobbyErrorData> EndLobbyErrorData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.LobbyErrorData>(o);
  }
  public LobbyErrorDataT UnPack() {
    var _o = new LobbyErrorDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LobbyErrorDataT _o) {
    _o.Error = this.Error;
  }
  public static Offset<Lobby.LobbyErrorData> Pack(FlatBufferBuilder builder, LobbyErrorDataT _o) {
    if (_o == null) return default(Offset<Lobby.LobbyErrorData>);
    var _Error = _o.Error == null ? default(StringOffset) : builder.CreateString(_o.Error);
    return CreateLobbyErrorData(
      builder,
      _Error);
  }
}

public class LobbyErrorDataT
{
  public string Error { get; set; }

  public LobbyErrorDataT() {
    this.Error = null;
  }
}


}
