// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MazeRewardBoxData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public MazeRewardBoxData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte SlotID { get { return __p.bb.Get(__p.bb_pos + 0); } }
  public int BoxID { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int ExpiredAt { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public bool IsOpened { get { return 0!=__p.bb.Get(__p.bb_pos + 12); } }

  public static Offset<Lobby.MazeRewardBoxData> CreateMazeRewardBoxData(FlatBufferBuilder builder, byte SlotID, int BoxID, int ExpiredAt, bool IsOpened) {
    builder.Prep(4, 16);
    builder.Pad(3);
    builder.PutBool(IsOpened);
    builder.PutInt(ExpiredAt);
    builder.PutInt(BoxID);
    builder.Pad(3);
    builder.PutByte(SlotID);
    return new Offset<Lobby.MazeRewardBoxData>(builder.Offset);
  }
  public MazeRewardBoxDataT UnPack() {
    var _o = new MazeRewardBoxDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MazeRewardBoxDataT _o) {
    _o.SlotID = this.SlotID;
    _o.BoxID = this.BoxID;
    _o.ExpiredAt = this.ExpiredAt;
    _o.IsOpened = this.IsOpened;
  }
  public static Offset<Lobby.MazeRewardBoxData> Pack(FlatBufferBuilder builder, MazeRewardBoxDataT _o) {
    if (_o == null) return default(Offset<Lobby.MazeRewardBoxData>);
    return CreateMazeRewardBoxData(
      builder,
      _o.SlotID,
      _o.BoxID,
      _o.ExpiredAt,
      _o.IsOpened);
  }
}

public class MazeRewardBoxDataT
{
  public byte SlotID { get; set; }
  public int BoxID { get; set; }
  public int ExpiredAt { get; set; }
  public bool IsOpened { get; set; }

  public MazeRewardBoxDataT() {
    this.SlotID = 0;
    this.BoxID = 0;
    this.ExpiredAt = 0;
    this.IsOpened = false;
  }
}


}
