// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MonsterData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public MonsterData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MonsterID { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Count { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<Lobby.MonsterData> CreateMonsterData(FlatBufferBuilder builder, int MonsterID, int Count) {
    builder.Prep(4, 8);
    builder.PutInt(Count);
    builder.PutInt(MonsterID);
    return new Offset<Lobby.MonsterData>(builder.Offset);
  }
  public MonsterDataT UnPack() {
    var _o = new MonsterDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MonsterDataT _o) {
    _o.MonsterID = this.MonsterID;
    _o.Count = this.Count;
  }
  public static Offset<Lobby.MonsterData> Pack(FlatBufferBuilder builder, MonsterDataT _o) {
    if (_o == null) return default(Offset<Lobby.MonsterData>);
    return CreateMonsterData(
      builder,
      _o.MonsterID,
      _o.Count);
  }
}

public class MonsterDataT
{
  public int MonsterID { get; set; }
  public int Count { get; set; }

  public MonsterDataT() {
    this.MonsterID = 0;
    this.Count = 0;
  }
}


}
