// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_ArtifactEnhance : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_ArtifactEnhance GetRootAsSA_ArtifactEnhance(ByteBuffer _bb) { return GetRootAsSA_ArtifactEnhance(_bb, new SA_ArtifactEnhance()); }
  public static SA_ArtifactEnhance GetRootAsSA_ArtifactEnhance(ByteBuffer _bb, SA_ArtifactEnhance obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_ArtifactEnhance __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.ArtifactData? ChangeArtifact { get { int o = __p.__offset(4); return o != 0 ? (Lobby.ArtifactData?)(new Lobby.ArtifactData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Lobby.AssetData? ChangeAssetList(int j) { int o = __p.__offset(6); return o != 0 ? (Lobby.AssetData?)(new Lobby.AssetData()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int ChangeAssetListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_ArtifactEnhance> CreateSA_ArtifactEnhance(FlatBufferBuilder builder,
      Lobby.ArtifactDataT ChangeArtifact = null,
      VectorOffset ChangeAssetListOffset = default(VectorOffset)) {
    builder.StartTable(2);
    SA_ArtifactEnhance.AddChangeAssetList(builder, ChangeAssetListOffset);
    SA_ArtifactEnhance.AddChangeArtifact(builder, Lobby.ArtifactData.Pack(builder, ChangeArtifact));
    return SA_ArtifactEnhance.EndSA_ArtifactEnhance(builder);
  }

  public static void StartSA_ArtifactEnhance(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddChangeArtifact(FlatBufferBuilder builder, Offset<Lobby.ArtifactData> ChangeArtifactOffset) { builder.AddStruct(0, ChangeArtifactOffset.Value, 0); }
  public static void AddChangeAssetList(FlatBufferBuilder builder, VectorOffset ChangeAssetListOffset) { builder.AddOffset(1, ChangeAssetListOffset.Value, 0); }
  public static void StartChangeAssetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<Lobby.SA_ArtifactEnhance> EndSA_ArtifactEnhance(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_ArtifactEnhance>(o);
  }
  public SA_ArtifactEnhanceT UnPack() {
    var _o = new SA_ArtifactEnhanceT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_ArtifactEnhanceT _o) {
    _o.ChangeArtifact = this.ChangeArtifact.HasValue ? this.ChangeArtifact.Value.UnPack() : null;
    _o.ChangeAssetList = new List<Lobby.AssetDataT>();
    for (var _j = 0; _j < this.ChangeAssetListLength; ++_j) {_o.ChangeAssetList.Add(this.ChangeAssetList(_j).HasValue ? this.ChangeAssetList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_ArtifactEnhance> Pack(FlatBufferBuilder builder, SA_ArtifactEnhanceT _o) {
    if (_o == null) return default(Offset<Lobby.SA_ArtifactEnhance>);
    var _ChangeAssetList = default(VectorOffset);
    if (_o.ChangeAssetList != null) {
      StartChangeAssetListVector(builder, _o.ChangeAssetList.Count);
      for (var _j = _o.ChangeAssetList.Count - 1; _j >= 0; --_j) { Lobby.AssetData.Pack(builder, _o.ChangeAssetList[_j]); }
      _ChangeAssetList = builder.EndVector();
    }
    return CreateSA_ArtifactEnhance(
      builder,
      _o.ChangeArtifact,
      _ChangeAssetList);
  }
}

public class SA_ArtifactEnhanceT
{
  public Lobby.ArtifactDataT ChangeArtifact { get; set; }
  public List<Lobby.AssetDataT> ChangeAssetList { get; set; }

  public SA_ArtifactEnhanceT() {
    this.ChangeArtifact = new Lobby.ArtifactDataT();
    this.ChangeAssetList = null;
  }
}


}
