// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_ArtifactDeckSlotDelete : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_ArtifactDeckSlotDelete GetRootAsSA_ArtifactDeckSlotDelete(ByteBuffer _bb) { return GetRootAsSA_ArtifactDeckSlotDelete(_bb, new SA_ArtifactDeckSlotDelete()); }
  public static SA_ArtifactDeckSlotDelete GetRootAsSA_ArtifactDeckSlotDelete(ByteBuffer _bb, SA_ArtifactDeckSlotDelete obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_ArtifactDeckSlotDelete __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_ArtifactDeckSlotDelete(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_ArtifactDeckSlotDelete> EndSA_ArtifactDeckSlotDelete(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_ArtifactDeckSlotDelete>(o);
  }
  public SA_ArtifactDeckSlotDeleteT UnPack() {
    var _o = new SA_ArtifactDeckSlotDeleteT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_ArtifactDeckSlotDeleteT _o) {
  }
  public static Offset<Lobby.SA_ArtifactDeckSlotDelete> Pack(FlatBufferBuilder builder, SA_ArtifactDeckSlotDeleteT _o) {
    if (_o == null) return default(Offset<Lobby.SA_ArtifactDeckSlotDelete>);
    StartSA_ArtifactDeckSlotDelete(builder);
    return EndSA_ArtifactDeckSlotDelete(builder);
  }
}

public class SA_ArtifactDeckSlotDeleteT
{

  public SA_ArtifactDeckSlotDeleteT() {
  }
}


}
