// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_AttendanceRecvReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_AttendanceRecvReward GetRootAsSA_AttendanceRecvReward(ByteBuffer _bb) { return GetRootAsSA_AttendanceRecvReward(_bb, new SA_AttendanceRecvReward()); }
  public static SA_AttendanceRecvReward GetRootAsSA_AttendanceRecvReward(ByteBuffer _bb, SA_AttendanceRecvReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_AttendanceRecvReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.AttendanceData? Attendance { get { int o = __p.__offset(4); return o != 0 ? (Lobby.AttendanceData?)(new Lobby.AttendanceData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Lobby.AssetData? ChangeAssetList(int j) { int o = __p.__offset(6); return o != 0 ? (Lobby.AssetData?)(new Lobby.AssetData()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int ChangeAssetListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.ItemData? ChangeItemList(int j) { int o = __p.__offset(8); return o != 0 ? (Lobby.ItemData?)(new Lobby.ItemData()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int ChangeItemListLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.HeroSkinData? ChangeHeroSkinList(int j) { int o = __p.__offset(10); return o != 0 ? (Lobby.HeroSkinData?)(new Lobby.HeroSkinData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChangeHeroSkinListLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_AttendanceRecvReward> CreateSA_AttendanceRecvReward(FlatBufferBuilder builder,
      Offset<Lobby.AttendanceData> AttendanceOffset = default(Offset<Lobby.AttendanceData>),
      VectorOffset ChangeAssetListOffset = default(VectorOffset),
      VectorOffset ChangeItemListOffset = default(VectorOffset),
      VectorOffset ChangeHeroSkinListOffset = default(VectorOffset)) {
    builder.StartTable(4);
    SA_AttendanceRecvReward.AddChangeHeroSkinList(builder, ChangeHeroSkinListOffset);
    SA_AttendanceRecvReward.AddChangeItemList(builder, ChangeItemListOffset);
    SA_AttendanceRecvReward.AddChangeAssetList(builder, ChangeAssetListOffset);
    SA_AttendanceRecvReward.AddAttendance(builder, AttendanceOffset);
    return SA_AttendanceRecvReward.EndSA_AttendanceRecvReward(builder);
  }

  public static void StartSA_AttendanceRecvReward(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddAttendance(FlatBufferBuilder builder, Offset<Lobby.AttendanceData> AttendanceOffset) { builder.AddOffset(0, AttendanceOffset.Value, 0); }
  public static void AddChangeAssetList(FlatBufferBuilder builder, VectorOffset ChangeAssetListOffset) { builder.AddOffset(1, ChangeAssetListOffset.Value, 0); }
  public static void StartChangeAssetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static void AddChangeItemList(FlatBufferBuilder builder, VectorOffset ChangeItemListOffset) { builder.AddOffset(2, ChangeItemListOffset.Value, 0); }
  public static void StartChangeItemListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddChangeHeroSkinList(FlatBufferBuilder builder, VectorOffset ChangeHeroSkinListOffset) { builder.AddOffset(3, ChangeHeroSkinListOffset.Value, 0); }
  public static VectorOffset CreateChangeHeroSkinListVector(FlatBufferBuilder builder, Offset<Lobby.HeroSkinData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChangeHeroSkinListVectorBlock(FlatBufferBuilder builder, Offset<Lobby.HeroSkinData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChangeHeroSkinListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Lobby.HeroSkinData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChangeHeroSkinListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Lobby.HeroSkinData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChangeHeroSkinListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Lobby.SA_AttendanceRecvReward> EndSA_AttendanceRecvReward(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_AttendanceRecvReward>(o);
  }
  public SA_AttendanceRecvRewardT UnPack() {
    var _o = new SA_AttendanceRecvRewardT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_AttendanceRecvRewardT _o) {
    _o.Attendance = this.Attendance.HasValue ? this.Attendance.Value.UnPack() : null;
    _o.ChangeAssetList = new List<Lobby.AssetDataT>();
    for (var _j = 0; _j < this.ChangeAssetListLength; ++_j) {_o.ChangeAssetList.Add(this.ChangeAssetList(_j).HasValue ? this.ChangeAssetList(_j).Value.UnPack() : null);}
    _o.ChangeItemList = new List<Lobby.ItemDataT>();
    for (var _j = 0; _j < this.ChangeItemListLength; ++_j) {_o.ChangeItemList.Add(this.ChangeItemList(_j).HasValue ? this.ChangeItemList(_j).Value.UnPack() : null);}
    _o.ChangeHeroSkinList = new List<Lobby.HeroSkinDataT>();
    for (var _j = 0; _j < this.ChangeHeroSkinListLength; ++_j) {_o.ChangeHeroSkinList.Add(this.ChangeHeroSkinList(_j).HasValue ? this.ChangeHeroSkinList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_AttendanceRecvReward> Pack(FlatBufferBuilder builder, SA_AttendanceRecvRewardT _o) {
    if (_o == null) return default(Offset<Lobby.SA_AttendanceRecvReward>);
    var _Attendance = _o.Attendance == null ? default(Offset<Lobby.AttendanceData>) : Lobby.AttendanceData.Pack(builder, _o.Attendance);
    var _ChangeAssetList = default(VectorOffset);
    if (_o.ChangeAssetList != null) {
      StartChangeAssetListVector(builder, _o.ChangeAssetList.Count);
      for (var _j = _o.ChangeAssetList.Count - 1; _j >= 0; --_j) { Lobby.AssetData.Pack(builder, _o.ChangeAssetList[_j]); }
      _ChangeAssetList = builder.EndVector();
    }
    var _ChangeItemList = default(VectorOffset);
    if (_o.ChangeItemList != null) {
      StartChangeItemListVector(builder, _o.ChangeItemList.Count);
      for (var _j = _o.ChangeItemList.Count - 1; _j >= 0; --_j) { Lobby.ItemData.Pack(builder, _o.ChangeItemList[_j]); }
      _ChangeItemList = builder.EndVector();
    }
    var _ChangeHeroSkinList = default(VectorOffset);
    if (_o.ChangeHeroSkinList != null) {
      var __ChangeHeroSkinList = new Offset<Lobby.HeroSkinData>[_o.ChangeHeroSkinList.Count];
      for (var _j = 0; _j < __ChangeHeroSkinList.Length; ++_j) { __ChangeHeroSkinList[_j] = Lobby.HeroSkinData.Pack(builder, _o.ChangeHeroSkinList[_j]); }
      _ChangeHeroSkinList = CreateChangeHeroSkinListVector(builder, __ChangeHeroSkinList);
    }
    return CreateSA_AttendanceRecvReward(
      builder,
      _Attendance,
      _ChangeAssetList,
      _ChangeItemList,
      _ChangeHeroSkinList);
  }
}

public class SA_AttendanceRecvRewardT
{
  public Lobby.AttendanceDataT Attendance { get; set; }
  public List<Lobby.AssetDataT> ChangeAssetList { get; set; }
  public List<Lobby.ItemDataT> ChangeItemList { get; set; }
  public List<Lobby.HeroSkinDataT> ChangeHeroSkinList { get; set; }

  public SA_AttendanceRecvRewardT() {
    this.Attendance = null;
    this.ChangeAssetList = null;
    this.ChangeItemList = null;
    this.ChangeHeroSkinList = null;
  }
}


}
