// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_BiskitLog : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_BiskitLog GetRootAsSA_BiskitLog(ByteBuffer _bb) { return GetRootAsSA_BiskitLog(_bb, new SA_BiskitLog()); }
  public static SA_BiskitLog GetRootAsSA_BiskitLog(ByteBuffer _bb, SA_BiskitLog obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_BiskitLog __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_BiskitLog(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_BiskitLog> EndSA_BiskitLog(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_BiskitLog>(o);
  }
  public SA_BiskitLogT UnPack() {
    var _o = new SA_BiskitLogT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_BiskitLogT _o) {
  }
  public static Offset<Lobby.SA_BiskitLog> Pack(FlatBufferBuilder builder, SA_BiskitLogT _o) {
    if (_o == null) return default(Offset<Lobby.SA_BiskitLog>);
    StartSA_BiskitLog(builder);
    return EndSA_BiskitLog(builder);
  }
}

public class SA_BiskitLogT
{

  public SA_BiskitLogT() {
  }
}


}
