// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_ChattingMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_ChattingMessage GetRootAsSA_ChattingMessage(ByteBuffer _bb) { return GetRootAsSA_ChattingMessage(_bb, new SA_ChattingMessage()); }
  public static SA_ChattingMessage GetRootAsSA_ChattingMessage(ByteBuffer _bb, SA_ChattingMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_ChattingMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_ChattingMessage(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_ChattingMessage> EndSA_ChattingMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_ChattingMessage>(o);
  }
  public SA_ChattingMessageT UnPack() {
    var _o = new SA_ChattingMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_ChattingMessageT _o) {
  }
  public static Offset<Lobby.SA_ChattingMessage> Pack(FlatBufferBuilder builder, SA_ChattingMessageT _o) {
    if (_o == null) return default(Offset<Lobby.SA_ChattingMessage>);
    StartSA_ChattingMessage(builder);
    return EndSA_ChattingMessage(builder);
  }
}

public class SA_ChattingMessageT
{

  public SA_ChattingMessageT() {
  }
}


}
