// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_CheatSuperAccount : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_CheatSuperAccount GetRootAsSA_CheatSuperAccount(ByteBuffer _bb) { return GetRootAsSA_CheatSuperAccount(_bb, new SA_CheatSuperAccount()); }
  public static SA_CheatSuperAccount GetRootAsSA_CheatSuperAccount(ByteBuffer _bb, SA_CheatSuperAccount obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_CheatSuperAccount __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.NewHeroData? NewHeroList(int j) { int o = __p.__offset(4); return o != 0 ? (Lobby.NewHeroData?)(new Lobby.NewHeroData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NewHeroListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.AssetData? ChangeAssetList(int j) { int o = __p.__offset(6); return o != 0 ? (Lobby.AssetData?)(new Lobby.AssetData()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int ChangeAssetListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.ItemData? ChangeItemList(int j) { int o = __p.__offset(8); return o != 0 ? (Lobby.ItemData?)(new Lobby.ItemData()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int ChangeItemListLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.HeroSkinData? ChangeHeroSkinList(int j) { int o = __p.__offset(10); return o != 0 ? (Lobby.HeroSkinData?)(new Lobby.HeroSkinData()).__assign(__p.__vector(o) + j * 20, __p.bb) : null; }
  public int ChangeHeroSkinListLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.PetData? ChangePetList(int j) { int o = __p.__offset(12); return o != 0 ? (Lobby.PetData?)(new Lobby.PetData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChangePetListLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Lobby.ArtifactData? ChangeArtifactList(int j) { int o = __p.__offset(14); return o != 0 ? (Lobby.ArtifactData?)(new Lobby.ArtifactData()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int ChangeArtifactListLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_CheatSuperAccount> CreateSA_CheatSuperAccount(FlatBufferBuilder builder,
      VectorOffset NewHeroListOffset = default(VectorOffset),
      VectorOffset ChangeAssetListOffset = default(VectorOffset),
      VectorOffset ChangeItemListOffset = default(VectorOffset),
      VectorOffset ChangeHeroSkinListOffset = default(VectorOffset),
      VectorOffset ChangePetListOffset = default(VectorOffset),
      VectorOffset ChangeArtifactListOffset = default(VectorOffset)) {
    builder.StartTable(6);
    SA_CheatSuperAccount.AddChangeArtifactList(builder, ChangeArtifactListOffset);
    SA_CheatSuperAccount.AddChangePetList(builder, ChangePetListOffset);
    SA_CheatSuperAccount.AddChangeHeroSkinList(builder, ChangeHeroSkinListOffset);
    SA_CheatSuperAccount.AddChangeItemList(builder, ChangeItemListOffset);
    SA_CheatSuperAccount.AddChangeAssetList(builder, ChangeAssetListOffset);
    SA_CheatSuperAccount.AddNewHeroList(builder, NewHeroListOffset);
    return SA_CheatSuperAccount.EndSA_CheatSuperAccount(builder);
  }

  public static void StartSA_CheatSuperAccount(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddNewHeroList(FlatBufferBuilder builder, VectorOffset NewHeroListOffset) { builder.AddOffset(0, NewHeroListOffset.Value, 0); }
  public static VectorOffset CreateNewHeroListVector(FlatBufferBuilder builder, Offset<Lobby.NewHeroData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNewHeroListVectorBlock(FlatBufferBuilder builder, Offset<Lobby.NewHeroData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNewHeroListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Lobby.NewHeroData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNewHeroListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Lobby.NewHeroData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartNewHeroListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddChangeAssetList(FlatBufferBuilder builder, VectorOffset ChangeAssetListOffset) { builder.AddOffset(1, ChangeAssetListOffset.Value, 0); }
  public static void StartChangeAssetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddChangeItemList(FlatBufferBuilder builder, VectorOffset ChangeItemListOffset) { builder.AddOffset(2, ChangeItemListOffset.Value, 0); }
  public static void StartChangeItemListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddChangeHeroSkinList(FlatBufferBuilder builder, VectorOffset ChangeHeroSkinListOffset) { builder.AddOffset(3, ChangeHeroSkinListOffset.Value, 0); }
  public static void StartChangeHeroSkinListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(20, numElems, 4); }
  public static void AddChangePetList(FlatBufferBuilder builder, VectorOffset ChangePetListOffset) { builder.AddOffset(4, ChangePetListOffset.Value, 0); }
  public static VectorOffset CreateChangePetListVector(FlatBufferBuilder builder, Offset<Lobby.PetData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChangePetListVectorBlock(FlatBufferBuilder builder, Offset<Lobby.PetData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChangePetListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Lobby.PetData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChangePetListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Lobby.PetData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChangePetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddChangeArtifactList(FlatBufferBuilder builder, VectorOffset ChangeArtifactListOffset) { builder.AddOffset(5, ChangeArtifactListOffset.Value, 0); }
  public static void StartChangeArtifactListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<Lobby.SA_CheatSuperAccount> EndSA_CheatSuperAccount(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_CheatSuperAccount>(o);
  }
  public SA_CheatSuperAccountT UnPack() {
    var _o = new SA_CheatSuperAccountT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_CheatSuperAccountT _o) {
    _o.NewHeroList = new List<Lobby.NewHeroDataT>();
    for (var _j = 0; _j < this.NewHeroListLength; ++_j) {_o.NewHeroList.Add(this.NewHeroList(_j).HasValue ? this.NewHeroList(_j).Value.UnPack() : null);}
    _o.ChangeAssetList = new List<Lobby.AssetDataT>();
    for (var _j = 0; _j < this.ChangeAssetListLength; ++_j) {_o.ChangeAssetList.Add(this.ChangeAssetList(_j).HasValue ? this.ChangeAssetList(_j).Value.UnPack() : null);}
    _o.ChangeItemList = new List<Lobby.ItemDataT>();
    for (var _j = 0; _j < this.ChangeItemListLength; ++_j) {_o.ChangeItemList.Add(this.ChangeItemList(_j).HasValue ? this.ChangeItemList(_j).Value.UnPack() : null);}
    _o.ChangeHeroSkinList = new List<Lobby.HeroSkinDataT>();
    for (var _j = 0; _j < this.ChangeHeroSkinListLength; ++_j) {_o.ChangeHeroSkinList.Add(this.ChangeHeroSkinList(_j).HasValue ? this.ChangeHeroSkinList(_j).Value.UnPack() : null);}
    _o.ChangePetList = new List<Lobby.PetDataT>();
    for (var _j = 0; _j < this.ChangePetListLength; ++_j) {_o.ChangePetList.Add(this.ChangePetList(_j).HasValue ? this.ChangePetList(_j).Value.UnPack() : null);}
    _o.ChangeArtifactList = new List<Lobby.ArtifactDataT>();
    for (var _j = 0; _j < this.ChangeArtifactListLength; ++_j) {_o.ChangeArtifactList.Add(this.ChangeArtifactList(_j).HasValue ? this.ChangeArtifactList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_CheatSuperAccount> Pack(FlatBufferBuilder builder, SA_CheatSuperAccountT _o) {
    if (_o == null) return default(Offset<Lobby.SA_CheatSuperAccount>);
    var _NewHeroList = default(VectorOffset);
    if (_o.NewHeroList != null) {
      var __NewHeroList = new Offset<Lobby.NewHeroData>[_o.NewHeroList.Count];
      for (var _j = 0; _j < __NewHeroList.Length; ++_j) { __NewHeroList[_j] = Lobby.NewHeroData.Pack(builder, _o.NewHeroList[_j]); }
      _NewHeroList = CreateNewHeroListVector(builder, __NewHeroList);
    }
    var _ChangeAssetList = default(VectorOffset);
    if (_o.ChangeAssetList != null) {
      StartChangeAssetListVector(builder, _o.ChangeAssetList.Count);
      for (var _j = _o.ChangeAssetList.Count - 1; _j >= 0; --_j) { Lobby.AssetData.Pack(builder, _o.ChangeAssetList[_j]); }
      _ChangeAssetList = builder.EndVector();
    }
    var _ChangeItemList = default(VectorOffset);
    if (_o.ChangeItemList != null) {
      StartChangeItemListVector(builder, _o.ChangeItemList.Count);
      for (var _j = _o.ChangeItemList.Count - 1; _j >= 0; --_j) { Lobby.ItemData.Pack(builder, _o.ChangeItemList[_j]); }
      _ChangeItemList = builder.EndVector();
    }
    var _ChangeHeroSkinList = default(VectorOffset);
    if (_o.ChangeHeroSkinList != null) {
      StartChangeHeroSkinListVector(builder, _o.ChangeHeroSkinList.Count);
      for (var _j = _o.ChangeHeroSkinList.Count - 1; _j >= 0; --_j) { Lobby.HeroSkinData.Pack(builder, _o.ChangeHeroSkinList[_j]); }
      _ChangeHeroSkinList = builder.EndVector();
    }
    var _ChangePetList = default(VectorOffset);
    if (_o.ChangePetList != null) {
      var __ChangePetList = new Offset<Lobby.PetData>[_o.ChangePetList.Count];
      for (var _j = 0; _j < __ChangePetList.Length; ++_j) { __ChangePetList[_j] = Lobby.PetData.Pack(builder, _o.ChangePetList[_j]); }
      _ChangePetList = CreateChangePetListVector(builder, __ChangePetList);
    }
    var _ChangeArtifactList = default(VectorOffset);
    if (_o.ChangeArtifactList != null) {
      StartChangeArtifactListVector(builder, _o.ChangeArtifactList.Count);
      for (var _j = _o.ChangeArtifactList.Count - 1; _j >= 0; --_j) { Lobby.ArtifactData.Pack(builder, _o.ChangeArtifactList[_j]); }
      _ChangeArtifactList = builder.EndVector();
    }
    return CreateSA_CheatSuperAccount(
      builder,
      _NewHeroList,
      _ChangeAssetList,
      _ChangeItemList,
      _ChangeHeroSkinList,
      _ChangePetList,
      _ChangeArtifactList);
  }
}

public class SA_CheatSuperAccountT
{
  public List<Lobby.NewHeroDataT> NewHeroList { get; set; }
  public List<Lobby.AssetDataT> ChangeAssetList { get; set; }
  public List<Lobby.ItemDataT> ChangeItemList { get; set; }
  public List<Lobby.HeroSkinDataT> ChangeHeroSkinList { get; set; }
  public List<Lobby.PetDataT> ChangePetList { get; set; }
  public List<Lobby.ArtifactDataT> ChangeArtifactList { get; set; }

  public SA_CheatSuperAccountT() {
    this.NewHeroList = null;
    this.ChangeAssetList = null;
    this.ChangeItemList = null;
    this.ChangeHeroSkinList = null;
    this.ChangePetList = null;
    this.ChangeArtifactList = null;
  }
}


}
