// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_CustomGameKickMember : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_CustomGameKickMember GetRootAsSA_CustomGameKickMember(ByteBuffer _bb) { return GetRootAsSA_CustomGameKickMember(_bb, new SA_CustomGameKickMember()); }
  public static SA_CustomGameKickMember GetRootAsSA_CustomGameKickMember(ByteBuffer _bb, SA_CustomGameKickMember obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_CustomGameKickMember __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_CustomGameKickMember(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_CustomGameKickMember> EndSA_CustomGameKickMember(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_CustomGameKickMember>(o);
  }
  public SA_CustomGameKickMemberT UnPack() {
    var _o = new SA_CustomGameKickMemberT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_CustomGameKickMemberT _o) {
  }
  public static Offset<Lobby.SA_CustomGameKickMember> Pack(FlatBufferBuilder builder, SA_CustomGameKickMemberT _o) {
    if (_o == null) return default(Offset<Lobby.SA_CustomGameKickMember>);
    StartSA_CustomGameKickMember(builder);
    return EndSA_CustomGameKickMember(builder);
  }
}

public class SA_CustomGameKickMemberT
{

  public SA_CustomGameKickMemberT() {
  }
}


}
