// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_EntitlementList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_EntitlementList GetRootAsSA_EntitlementList(ByteBuffer _bb) { return GetRootAsSA_EntitlementList(_bb, new SA_EntitlementList()); }
  public static SA_EntitlementList GetRootAsSA_EntitlementList(ByteBuffer _bb, SA_EntitlementList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_EntitlementList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EntitlementList(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int EntitlementListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetEntitlementListBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetEntitlementListBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetEntitlementListArray() { return __p.__vector_as_array<int>(4); }

  public static Offset<Lobby.SA_EntitlementList> CreateSA_EntitlementList(FlatBufferBuilder builder,
      VectorOffset EntitlementListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SA_EntitlementList.AddEntitlementList(builder, EntitlementListOffset);
    return SA_EntitlementList.EndSA_EntitlementList(builder);
  }

  public static void StartSA_EntitlementList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEntitlementList(FlatBufferBuilder builder, VectorOffset EntitlementListOffset) { builder.AddOffset(0, EntitlementListOffset.Value, 0); }
  public static VectorOffset CreateEntitlementListVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEntitlementListVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntitlementListVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntitlementListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEntitlementListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Lobby.SA_EntitlementList> EndSA_EntitlementList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_EntitlementList>(o);
  }
  public SA_EntitlementListT UnPack() {
    var _o = new SA_EntitlementListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_EntitlementListT _o) {
    _o.EntitlementList = new List<int>();
    for (var _j = 0; _j < this.EntitlementListLength; ++_j) {_o.EntitlementList.Add(this.EntitlementList(_j));}
  }
  public static Offset<Lobby.SA_EntitlementList> Pack(FlatBufferBuilder builder, SA_EntitlementListT _o) {
    if (_o == null) return default(Offset<Lobby.SA_EntitlementList>);
    var _EntitlementList = default(VectorOffset);
    if (_o.EntitlementList != null) {
      var __EntitlementList = _o.EntitlementList.ToArray();
      _EntitlementList = CreateEntitlementListVector(builder, __EntitlementList);
    }
    return CreateSA_EntitlementList(
      builder,
      _EntitlementList);
  }
}

public class SA_EntitlementListT
{
  public List<int> EntitlementList { get; set; }

  public SA_EntitlementListT() {
    this.EntitlementList = null;
  }
}


}
