// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_GuideMissionReceiveProgressReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_GuideMissionReceiveProgressReward GetRootAsSA_GuideMissionReceiveProgressReward(ByteBuffer _bb) { return GetRootAsSA_GuideMissionReceiveProgressReward(_bb, new SA_GuideMissionReceiveProgressReward()); }
  public static SA_GuideMissionReceiveProgressReward GetRootAsSA_GuideMissionReceiveProgressReward(ByteBuffer _bb, SA_GuideMissionReceiveProgressReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_GuideMissionReceiveProgressReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int LastReceiveID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Lobby.NewHeroData? NewHero { get { int o = __p.__offset(6); return o != 0 ? (Lobby.NewHeroData?)(new Lobby.NewHeroData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.SA_GuideMissionReceiveProgressReward> CreateSA_GuideMissionReceiveProgressReward(FlatBufferBuilder builder,
      int LastReceiveID = 0,
      Offset<Lobby.NewHeroData> NewHeroOffset = default(Offset<Lobby.NewHeroData>)) {
    builder.StartTable(2);
    SA_GuideMissionReceiveProgressReward.AddNewHero(builder, NewHeroOffset);
    SA_GuideMissionReceiveProgressReward.AddLastReceiveID(builder, LastReceiveID);
    return SA_GuideMissionReceiveProgressReward.EndSA_GuideMissionReceiveProgressReward(builder);
  }

  public static void StartSA_GuideMissionReceiveProgressReward(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLastReceiveID(FlatBufferBuilder builder, int LastReceiveID) { builder.AddInt(0, LastReceiveID, 0); }
  public static void AddNewHero(FlatBufferBuilder builder, Offset<Lobby.NewHeroData> NewHeroOffset) { builder.AddOffset(1, NewHeroOffset.Value, 0); }
  public static Offset<Lobby.SA_GuideMissionReceiveProgressReward> EndSA_GuideMissionReceiveProgressReward(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_GuideMissionReceiveProgressReward>(o);
  }
  public SA_GuideMissionReceiveProgressRewardT UnPack() {
    var _o = new SA_GuideMissionReceiveProgressRewardT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_GuideMissionReceiveProgressRewardT _o) {
    _o.LastReceiveID = this.LastReceiveID;
    _o.NewHero = this.NewHero.HasValue ? this.NewHero.Value.UnPack() : null;
  }
  public static Offset<Lobby.SA_GuideMissionReceiveProgressReward> Pack(FlatBufferBuilder builder, SA_GuideMissionReceiveProgressRewardT _o) {
    if (_o == null) return default(Offset<Lobby.SA_GuideMissionReceiveProgressReward>);
    var _NewHero = _o.NewHero == null ? default(Offset<Lobby.NewHeroData>) : Lobby.NewHeroData.Pack(builder, _o.NewHero);
    return CreateSA_GuideMissionReceiveProgressReward(
      builder,
      _o.LastReceiveID,
      _NewHero);
  }
}

public class SA_GuideMissionReceiveProgressRewardT
{
  public int LastReceiveID { get; set; }
  public Lobby.NewHeroDataT NewHero { get; set; }

  public SA_GuideMissionReceiveProgressRewardT() {
    this.LastReceiveID = 0;
    this.NewHero = null;
  }
}


}
