// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_HeroSkinPresetList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_HeroSkinPresetList GetRootAsSA_HeroSkinPresetList(ByteBuffer _bb) { return GetRootAsSA_HeroSkinPresetList(_bb, new SA_HeroSkinPresetList()); }
  public static SA_HeroSkinPresetList GetRootAsSA_HeroSkinPresetList(ByteBuffer _bb, SA_HeroSkinPresetList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_HeroSkinPresetList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.HeroSkinPresetData? HeroSkinPresetList(int j) { int o = __p.__offset(4); return o != 0 ? (Lobby.HeroSkinPresetData?)(new Lobby.HeroSkinPresetData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HeroSkinPresetListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_HeroSkinPresetList> CreateSA_HeroSkinPresetList(FlatBufferBuilder builder,
      VectorOffset HeroSkinPresetListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SA_HeroSkinPresetList.AddHeroSkinPresetList(builder, HeroSkinPresetListOffset);
    return SA_HeroSkinPresetList.EndSA_HeroSkinPresetList(builder);
  }

  public static void StartSA_HeroSkinPresetList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHeroSkinPresetList(FlatBufferBuilder builder, VectorOffset HeroSkinPresetListOffset) { builder.AddOffset(0, HeroSkinPresetListOffset.Value, 0); }
  public static VectorOffset CreateHeroSkinPresetListVector(FlatBufferBuilder builder, Offset<Lobby.HeroSkinPresetData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHeroSkinPresetListVectorBlock(FlatBufferBuilder builder, Offset<Lobby.HeroSkinPresetData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeroSkinPresetListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Lobby.HeroSkinPresetData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeroSkinPresetListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Lobby.HeroSkinPresetData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartHeroSkinPresetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Lobby.SA_HeroSkinPresetList> EndSA_HeroSkinPresetList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_HeroSkinPresetList>(o);
  }
  public SA_HeroSkinPresetListT UnPack() {
    var _o = new SA_HeroSkinPresetListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_HeroSkinPresetListT _o) {
    _o.HeroSkinPresetList = new List<Lobby.HeroSkinPresetDataT>();
    for (var _j = 0; _j < this.HeroSkinPresetListLength; ++_j) {_o.HeroSkinPresetList.Add(this.HeroSkinPresetList(_j).HasValue ? this.HeroSkinPresetList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_HeroSkinPresetList> Pack(FlatBufferBuilder builder, SA_HeroSkinPresetListT _o) {
    if (_o == null) return default(Offset<Lobby.SA_HeroSkinPresetList>);
    var _HeroSkinPresetList = default(VectorOffset);
    if (_o.HeroSkinPresetList != null) {
      var __HeroSkinPresetList = new Offset<Lobby.HeroSkinPresetData>[_o.HeroSkinPresetList.Count];
      for (var _j = 0; _j < __HeroSkinPresetList.Length; ++_j) { __HeroSkinPresetList[_j] = Lobby.HeroSkinPresetData.Pack(builder, _o.HeroSkinPresetList[_j]); }
      _HeroSkinPresetList = CreateHeroSkinPresetListVector(builder, __HeroSkinPresetList);
    }
    return CreateSA_HeroSkinPresetList(
      builder,
      _HeroSkinPresetList);
  }
}

public class SA_HeroSkinPresetListT
{
  public List<Lobby.HeroSkinPresetDataT> HeroSkinPresetList { get; set; }

  public SA_HeroSkinPresetListT() {
    this.HeroSkinPresetList = null;
  }
}


}
