// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_HeroSkinPresetSlotBuy : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_HeroSkinPresetSlotBuy GetRootAsSA_HeroSkinPresetSlotBuy(ByteBuffer _bb) { return GetRootAsSA_HeroSkinPresetSlotBuy(_bb, new SA_HeroSkinPresetSlotBuy()); }
  public static SA_HeroSkinPresetSlotBuy GetRootAsSA_HeroSkinPresetSlotBuy(ByteBuffer _bb, SA_HeroSkinPresetSlotBuy obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_HeroSkinPresetSlotBuy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int HeroID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AddPresetCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Lobby.AssetData? ChangeAssetList(int j) { int o = __p.__offset(8); return o != 0 ? (Lobby.AssetData?)(new Lobby.AssetData()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int ChangeAssetListLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_HeroSkinPresetSlotBuy> CreateSA_HeroSkinPresetSlotBuy(FlatBufferBuilder builder,
      int HeroID = 0,
      int AddPresetCount = 0,
      VectorOffset ChangeAssetListOffset = default(VectorOffset)) {
    builder.StartTable(3);
    SA_HeroSkinPresetSlotBuy.AddChangeAssetList(builder, ChangeAssetListOffset);
    SA_HeroSkinPresetSlotBuy.AddAddPresetCount(builder, AddPresetCount);
    SA_HeroSkinPresetSlotBuy.AddHeroID(builder, HeroID);
    return SA_HeroSkinPresetSlotBuy.EndSA_HeroSkinPresetSlotBuy(builder);
  }

  public static void StartSA_HeroSkinPresetSlotBuy(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(0, HeroID, 0); }
  public static void AddAddPresetCount(FlatBufferBuilder builder, int AddPresetCount) { builder.AddInt(1, AddPresetCount, 0); }
  public static void AddChangeAssetList(FlatBufferBuilder builder, VectorOffset ChangeAssetListOffset) { builder.AddOffset(2, ChangeAssetListOffset.Value, 0); }
  public static void StartChangeAssetListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<Lobby.SA_HeroSkinPresetSlotBuy> EndSA_HeroSkinPresetSlotBuy(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_HeroSkinPresetSlotBuy>(o);
  }
  public SA_HeroSkinPresetSlotBuyT UnPack() {
    var _o = new SA_HeroSkinPresetSlotBuyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_HeroSkinPresetSlotBuyT _o) {
    _o.HeroID = this.HeroID;
    _o.AddPresetCount = this.AddPresetCount;
    _o.ChangeAssetList = new List<Lobby.AssetDataT>();
    for (var _j = 0; _j < this.ChangeAssetListLength; ++_j) {_o.ChangeAssetList.Add(this.ChangeAssetList(_j).HasValue ? this.ChangeAssetList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_HeroSkinPresetSlotBuy> Pack(FlatBufferBuilder builder, SA_HeroSkinPresetSlotBuyT _o) {
    if (_o == null) return default(Offset<Lobby.SA_HeroSkinPresetSlotBuy>);
    var _ChangeAssetList = default(VectorOffset);
    if (_o.ChangeAssetList != null) {
      StartChangeAssetListVector(builder, _o.ChangeAssetList.Count);
      for (var _j = _o.ChangeAssetList.Count - 1; _j >= 0; --_j) { Lobby.AssetData.Pack(builder, _o.ChangeAssetList[_j]); }
      _ChangeAssetList = builder.EndVector();
    }
    return CreateSA_HeroSkinPresetSlotBuy(
      builder,
      _o.HeroID,
      _o.AddPresetCount,
      _ChangeAssetList);
  }
}

public class SA_HeroSkinPresetSlotBuyT
{
  public int HeroID { get; set; }
  public int AddPresetCount { get; set; }
  public List<Lobby.AssetDataT> ChangeAssetList { get; set; }

  public SA_HeroSkinPresetSlotBuyT() {
    this.HeroID = 0;
    this.AddPresetCount = 0;
    this.ChangeAssetList = null;
  }
}


}
