// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_PartyKickMember : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_PartyKickMember GetRootAsSA_PartyKickMember(ByteBuffer _bb) { return GetRootAsSA_PartyKickMember(_bb, new SA_PartyKickMember()); }
  public static SA_PartyKickMember GetRootAsSA_PartyKickMember(ByteBuffer _bb, SA_PartyKickMember obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_PartyKickMember __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_PartyKickMember(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_PartyKickMember> EndSA_PartyKickMember(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_PartyKickMember>(o);
  }
  public SA_PartyKickMemberT UnPack() {
    var _o = new SA_PartyKickMemberT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_PartyKickMemberT _o) {
  }
  public static Offset<Lobby.SA_PartyKickMember> Pack(FlatBufferBuilder builder, SA_PartyKickMemberT _o) {
    if (_o == null) return default(Offset<Lobby.SA_PartyKickMember>);
    StartSA_PartyKickMember(builder);
    return EndSA_PartyKickMember(builder);
  }
}

public class SA_PartyKickMemberT
{

  public SA_PartyKickMemberT() {
  }
}


}
