// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_PlayRecordRpgChapterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_PlayRecordRpgChapterList GetRootAsSA_PlayRecordRpgChapterList(ByteBuffer _bb) { return GetRootAsSA_PlayRecordRpgChapterList(_bb, new SA_PlayRecordRpgChapterList()); }
  public static SA_PlayRecordRpgChapterList GetRootAsSA_PlayRecordRpgChapterList(ByteBuffer _bb, SA_PlayRecordRpgChapterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_PlayRecordRpgChapterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ChapterIDList(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ChapterIDListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetChapterIDListBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetChapterIDListBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetChapterIDListArray() { return __p.__vector_as_array<int>(4); }

  public static Offset<Lobby.SA_PlayRecordRpgChapterList> CreateSA_PlayRecordRpgChapterList(FlatBufferBuilder builder,
      VectorOffset ChapterIDListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SA_PlayRecordRpgChapterList.AddChapterIDList(builder, ChapterIDListOffset);
    return SA_PlayRecordRpgChapterList.EndSA_PlayRecordRpgChapterList(builder);
  }

  public static void StartSA_PlayRecordRpgChapterList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddChapterIDList(FlatBufferBuilder builder, VectorOffset ChapterIDListOffset) { builder.AddOffset(0, ChapterIDListOffset.Value, 0); }
  public static VectorOffset CreateChapterIDListVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateChapterIDListVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChapterIDListVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChapterIDListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChapterIDListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Lobby.SA_PlayRecordRpgChapterList> EndSA_PlayRecordRpgChapterList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_PlayRecordRpgChapterList>(o);
  }
  public SA_PlayRecordRpgChapterListT UnPack() {
    var _o = new SA_PlayRecordRpgChapterListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_PlayRecordRpgChapterListT _o) {
    _o.ChapterIDList = new List<int>();
    for (var _j = 0; _j < this.ChapterIDListLength; ++_j) {_o.ChapterIDList.Add(this.ChapterIDList(_j));}
  }
  public static Offset<Lobby.SA_PlayRecordRpgChapterList> Pack(FlatBufferBuilder builder, SA_PlayRecordRpgChapterListT _o) {
    if (_o == null) return default(Offset<Lobby.SA_PlayRecordRpgChapterList>);
    var _ChapterIDList = default(VectorOffset);
    if (_o.ChapterIDList != null) {
      var __ChapterIDList = _o.ChapterIDList.ToArray();
      _ChapterIDList = CreateChapterIDListVector(builder, __ChapterIDList);
    }
    return CreateSA_PlayRecordRpgChapterList(
      builder,
      _ChapterIDList);
  }
}

public class SA_PlayRecordRpgChapterListT
{
  public List<int> ChapterIDList { get; set; }

  public SA_PlayRecordRpgChapterListT() {
    this.ChapterIDList = null;
  }
}


}
