// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_PetFeed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_PetFeed GetRootAsSA_PetFeed(ByteBuffer _bb) { return GetRootAsSA_PetFeed(_bb, new SA_PetFeed()); }
  public static SA_PetFeed GetRootAsSA_PetFeed(ByteBuffer _bb, SA_PetFeed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_PetFeed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.PetData? Pet { get { int o = __p.__offset(4); return o != 0 ? (Lobby.PetData?)(new Lobby.PetData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Lobby.ItemData? ChangeItemList(int j) { int o = __p.__offset(6); return o != 0 ? (Lobby.ItemData?)(new Lobby.ItemData()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int ChangeItemListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_PetFeed> CreateSA_PetFeed(FlatBufferBuilder builder,
      Offset<Lobby.PetData> PetOffset = default(Offset<Lobby.PetData>),
      VectorOffset ChangeItemListOffset = default(VectorOffset)) {
    builder.StartTable(2);
    SA_PetFeed.AddChangeItemList(builder, ChangeItemListOffset);
    SA_PetFeed.AddPet(builder, PetOffset);
    return SA_PetFeed.EndSA_PetFeed(builder);
  }

  public static void StartSA_PetFeed(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPet(FlatBufferBuilder builder, Offset<Lobby.PetData> PetOffset) { builder.AddOffset(0, PetOffset.Value, 0); }
  public static void AddChangeItemList(FlatBufferBuilder builder, VectorOffset ChangeItemListOffset) { builder.AddOffset(1, ChangeItemListOffset.Value, 0); }
  public static void StartChangeItemListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static Offset<Lobby.SA_PetFeed> EndSA_PetFeed(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_PetFeed>(o);
  }
  public SA_PetFeedT UnPack() {
    var _o = new SA_PetFeedT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_PetFeedT _o) {
    _o.Pet = this.Pet.HasValue ? this.Pet.Value.UnPack() : null;
    _o.ChangeItemList = new List<Lobby.ItemDataT>();
    for (var _j = 0; _j < this.ChangeItemListLength; ++_j) {_o.ChangeItemList.Add(this.ChangeItemList(_j).HasValue ? this.ChangeItemList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_PetFeed> Pack(FlatBufferBuilder builder, SA_PetFeedT _o) {
    if (_o == null) return default(Offset<Lobby.SA_PetFeed>);
    var _Pet = _o.Pet == null ? default(Offset<Lobby.PetData>) : Lobby.PetData.Pack(builder, _o.Pet);
    var _ChangeItemList = default(VectorOffset);
    if (_o.ChangeItemList != null) {
      StartChangeItemListVector(builder, _o.ChangeItemList.Count);
      for (var _j = _o.ChangeItemList.Count - 1; _j >= 0; --_j) { Lobby.ItemData.Pack(builder, _o.ChangeItemList[_j]); }
      _ChangeItemList = builder.EndVector();
    }
    return CreateSA_PetFeed(
      builder,
      _Pet,
      _ChangeItemList);
  }
}

public class SA_PetFeedT
{
  public Lobby.PetDataT Pet { get; set; }
  public List<Lobby.ItemDataT> ChangeItemList { get; set; }

  public SA_PetFeedT() {
    this.Pet = null;
    this.ChangeItemList = null;
  }
}


}
