// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_PetLock : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_PetLock GetRootAsSA_PetLock(ByteBuffer _bb) { return GetRootAsSA_PetLock(_bb, new SA_PetLock()); }
  public static SA_PetLock GetRootAsSA_PetLock(ByteBuffer _bb, SA_PetLock obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_PetLock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.PetData? Pet { get { int o = __p.__offset(4); return o != 0 ? (Lobby.PetData?)(new Lobby.PetData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.SA_PetLock> CreateSA_PetLock(FlatBufferBuilder builder,
      Offset<Lobby.PetData> PetOffset = default(Offset<Lobby.PetData>)) {
    builder.StartTable(1);
    SA_PetLock.AddPet(builder, PetOffset);
    return SA_PetLock.EndSA_PetLock(builder);
  }

  public static void StartSA_PetLock(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPet(FlatBufferBuilder builder, Offset<Lobby.PetData> PetOffset) { builder.AddOffset(0, PetOffset.Value, 0); }
  public static Offset<Lobby.SA_PetLock> EndSA_PetLock(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_PetLock>(o);
  }
  public SA_PetLockT UnPack() {
    var _o = new SA_PetLockT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_PetLockT _o) {
    _o.Pet = this.Pet.HasValue ? this.Pet.Value.UnPack() : null;
  }
  public static Offset<Lobby.SA_PetLock> Pack(FlatBufferBuilder builder, SA_PetLockT _o) {
    if (_o == null) return default(Offset<Lobby.SA_PetLock>);
    var _Pet = _o.Pet == null ? default(Offset<Lobby.PetData>) : Lobby.PetData.Pack(builder, _o.Pet);
    return CreateSA_PetLock(
      builder,
      _Pet);
  }
}

public class SA_PetLockT
{
  public Lobby.PetDataT Pet { get; set; }

  public SA_PetLockT() {
    this.Pet = null;
  }
}


}
