// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_RecommendUserList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_RecommendUserList GetRootAsSA_RecommendUserList(ByteBuffer _bb) { return GetRootAsSA_RecommendUserList(_bb, new SA_RecommendUserList()); }
  public static SA_RecommendUserList GetRootAsSA_RecommendUserList(ByteBuffer _bb, SA_RecommendUserList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_RecommendUserList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.RecommendUserInfo? RecommendUserList(int j) { int o = __p.__offset(4); return o != 0 ? (Lobby.RecommendUserInfo?)(new Lobby.RecommendUserInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RecommendUserListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SA_RecommendUserList> CreateSA_RecommendUserList(FlatBufferBuilder builder,
      VectorOffset RecommendUserListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SA_RecommendUserList.AddRecommendUserList(builder, RecommendUserListOffset);
    return SA_RecommendUserList.EndSA_RecommendUserList(builder);
  }

  public static void StartSA_RecommendUserList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRecommendUserList(FlatBufferBuilder builder, VectorOffset RecommendUserListOffset) { builder.AddOffset(0, RecommendUserListOffset.Value, 0); }
  public static VectorOffset CreateRecommendUserListVector(FlatBufferBuilder builder, Offset<Lobby.RecommendUserInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRecommendUserListVectorBlock(FlatBufferBuilder builder, Offset<Lobby.RecommendUserInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRecommendUserListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Lobby.RecommendUserInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRecommendUserListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Lobby.RecommendUserInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRecommendUserListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Lobby.SA_RecommendUserList> EndSA_RecommendUserList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_RecommendUserList>(o);
  }
  public SA_RecommendUserListT UnPack() {
    var _o = new SA_RecommendUserListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_RecommendUserListT _o) {
    _o.RecommendUserList = new List<Lobby.RecommendUserInfoT>();
    for (var _j = 0; _j < this.RecommendUserListLength; ++_j) {_o.RecommendUserList.Add(this.RecommendUserList(_j).HasValue ? this.RecommendUserList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SA_RecommendUserList> Pack(FlatBufferBuilder builder, SA_RecommendUserListT _o) {
    if (_o == null) return default(Offset<Lobby.SA_RecommendUserList>);
    var _RecommendUserList = default(VectorOffset);
    if (_o.RecommendUserList != null) {
      var __RecommendUserList = new Offset<Lobby.RecommendUserInfo>[_o.RecommendUserList.Count];
      for (var _j = 0; _j < __RecommendUserList.Length; ++_j) { __RecommendUserList[_j] = Lobby.RecommendUserInfo.Pack(builder, _o.RecommendUserList[_j]); }
      _RecommendUserList = CreateRecommendUserListVector(builder, __RecommendUserList);
    }
    return CreateSA_RecommendUserList(
      builder,
      _RecommendUserList);
  }
}

public class SA_RecommendUserListT
{
  public List<Lobby.RecommendUserInfoT> RecommendUserList { get; set; }

  public SA_RecommendUserListT() {
    this.RecommendUserList = null;
  }
}


}
