// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_SeasonPassDirectionOff : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_SeasonPassDirectionOff GetRootAsSA_SeasonPassDirectionOff(ByteBuffer _bb) { return GetRootAsSA_SeasonPassDirectionOff(_bb, new SA_SeasonPassDirectionOff()); }
  public static SA_SeasonPassDirectionOff GetRootAsSA_SeasonPassDirectionOff(ByteBuffer _bb, SA_SeasonPassDirectionOff obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_SeasonPassDirectionOff __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_SeasonPassDirectionOff(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_SeasonPassDirectionOff> EndSA_SeasonPassDirectionOff(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_SeasonPassDirectionOff>(o);
  }
  public SA_SeasonPassDirectionOffT UnPack() {
    var _o = new SA_SeasonPassDirectionOffT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_SeasonPassDirectionOffT _o) {
  }
  public static Offset<Lobby.SA_SeasonPassDirectionOff> Pack(FlatBufferBuilder builder, SA_SeasonPassDirectionOffT _o) {
    if (_o == null) return default(Offset<Lobby.SA_SeasonPassDirectionOff>);
    StartSA_SeasonPassDirectionOff(builder);
    return EndSA_SeasonPassDirectionOff(builder);
  }
}

public class SA_SeasonPassDirectionOffT
{

  public SA_SeasonPassDirectionOffT() {
  }
}


}
