// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_VehicleRecall : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_VehicleRecall GetRootAsSA_VehicleRecall(ByteBuffer _bb) { return GetRootAsSA_VehicleRecall(_bb, new SA_VehicleRecall()); }
  public static SA_VehicleRecall GetRootAsSA_VehicleRecall(ByteBuffer _bb, SA_VehicleRecall obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_VehicleRecall __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSA_VehicleRecall(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Lobby.SA_VehicleRecall> EndSA_VehicleRecall(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_VehicleRecall>(o);
  }
  public SA_VehicleRecallT UnPack() {
    var _o = new SA_VehicleRecallT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_VehicleRecallT _o) {
  }
  public static Offset<Lobby.SA_VehicleRecall> Pack(FlatBufferBuilder builder, SA_VehicleRecallT _o) {
    if (_o == null) return default(Offset<Lobby.SA_VehicleRecall>);
    StartSA_VehicleRecall(builder);
    return EndSA_VehicleRecall(builder);
  }
}

public class SA_VehicleRecallT
{

  public SA_VehicleRecallT() {
  }
}


}
