// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_VehicleEquipSlot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_VehicleEquipSlot GetRootAsSA_VehicleEquipSlot(ByteBuffer _bb) { return GetRootAsSA_VehicleEquipSlot(_bb, new SA_VehicleEquipSlot()); }
  public static SA_VehicleEquipSlot GetRootAsSA_VehicleEquipSlot(ByteBuffer _bb, SA_VehicleEquipSlot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_VehicleEquipSlot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int VehicleID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.SA_VehicleEquipSlot> CreateSA_VehicleEquipSlot(FlatBufferBuilder builder,
      int VehicleID = 0) {
    builder.StartTable(1);
    SA_VehicleEquipSlot.AddVehicleID(builder, VehicleID);
    return SA_VehicleEquipSlot.EndSA_VehicleEquipSlot(builder);
  }

  public static void StartSA_VehicleEquipSlot(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddVehicleID(FlatBufferBuilder builder, int VehicleID) { builder.AddInt(0, VehicleID, 0); }
  public static Offset<Lobby.SA_VehicleEquipSlot> EndSA_VehicleEquipSlot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_VehicleEquipSlot>(o);
  }
  public SA_VehicleEquipSlotT UnPack() {
    var _o = new SA_VehicleEquipSlotT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_VehicleEquipSlotT _o) {
    _o.VehicleID = this.VehicleID;
  }
  public static Offset<Lobby.SA_VehicleEquipSlot> Pack(FlatBufferBuilder builder, SA_VehicleEquipSlotT _o) {
    if (_o == null) return default(Offset<Lobby.SA_VehicleEquipSlot>);
    return CreateSA_VehicleEquipSlot(
      builder,
      _o.VehicleID);
  }
}

public class SA_VehicleEquipSlotT
{
  public int VehicleID { get; set; }

  public SA_VehicleEquipSlotT() {
    this.VehicleID = 0;
  }
}


}
