// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_VehicleRaceCheck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_VehicleRaceCheck GetRootAsSA_VehicleRaceCheck(ByteBuffer _bb) { return GetRootAsSA_VehicleRaceCheck(_bb, new SA_VehicleRaceCheck()); }
  public static SA_VehicleRaceCheck GetRootAsSA_VehicleRaceCheck(ByteBuffer _bb, SA_VehicleRaceCheck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_VehicleRaceCheck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool IsBlock { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Lobby.SA_VehicleRaceCheck> CreateSA_VehicleRaceCheck(FlatBufferBuilder builder,
      bool IsBlock = false) {
    builder.StartTable(1);
    SA_VehicleRaceCheck.AddIsBlock(builder, IsBlock);
    return SA_VehicleRaceCheck.EndSA_VehicleRaceCheck(builder);
  }

  public static void StartSA_VehicleRaceCheck(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIsBlock(FlatBufferBuilder builder, bool IsBlock) { builder.AddBool(0, IsBlock, false); }
  public static Offset<Lobby.SA_VehicleRaceCheck> EndSA_VehicleRaceCheck(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_VehicleRaceCheck>(o);
  }
  public SA_VehicleRaceCheckT UnPack() {
    var _o = new SA_VehicleRaceCheckT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_VehicleRaceCheckT _o) {
    _o.IsBlock = this.IsBlock;
  }
  public static Offset<Lobby.SA_VehicleRaceCheck> Pack(FlatBufferBuilder builder, SA_VehicleRaceCheckT _o) {
    if (_o == null) return default(Offset<Lobby.SA_VehicleRaceCheck>);
    return CreateSA_VehicleRaceCheck(
      builder,
      _o.IsBlock);
  }
}

public class SA_VehicleRaceCheckT
{
  public bool IsBlock { get; set; }

  public SA_VehicleRaceCheckT() {
    this.IsBlock = false;
  }
}


}
