// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SA_WonderCubePointReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SA_WonderCubePointReward GetRootAsSA_WonderCubePointReward(ByteBuffer _bb) { return GetRootAsSA_WonderCubePointReward(_bb, new SA_WonderCubePointReward()); }
  public static SA_WonderCubePointReward GetRootAsSA_WonderCubePointReward(ByteBuffer _bb, SA_WonderCubePointReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SA_WonderCubePointReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int WonderCubePointID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public sbyte RewardLevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public Lobby.RewardData? RewardInfo { get { int o = __p.__offset(8); return o != 0 ? (Lobby.RewardData?)(new Lobby.RewardData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Lobby.SA_WonderCubePointReward> CreateSA_WonderCubePointReward(FlatBufferBuilder builder,
      int WonderCubePointID = 0,
      sbyte RewardLevel = 0,
      Offset<Lobby.RewardData> RewardInfoOffset = default(Offset<Lobby.RewardData>)) {
    builder.StartTable(3);
    SA_WonderCubePointReward.AddRewardInfo(builder, RewardInfoOffset);
    SA_WonderCubePointReward.AddWonderCubePointID(builder, WonderCubePointID);
    SA_WonderCubePointReward.AddRewardLevel(builder, RewardLevel);
    return SA_WonderCubePointReward.EndSA_WonderCubePointReward(builder);
  }

  public static void StartSA_WonderCubePointReward(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddWonderCubePointID(FlatBufferBuilder builder, int WonderCubePointID) { builder.AddInt(0, WonderCubePointID, 0); }
  public static void AddRewardLevel(FlatBufferBuilder builder, sbyte RewardLevel) { builder.AddSbyte(1, RewardLevel, 0); }
  public static void AddRewardInfo(FlatBufferBuilder builder, Offset<Lobby.RewardData> RewardInfoOffset) { builder.AddOffset(2, RewardInfoOffset.Value, 0); }
  public static Offset<Lobby.SA_WonderCubePointReward> EndSA_WonderCubePointReward(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SA_WonderCubePointReward>(o);
  }
  public SA_WonderCubePointRewardT UnPack() {
    var _o = new SA_WonderCubePointRewardT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SA_WonderCubePointRewardT _o) {
    _o.WonderCubePointID = this.WonderCubePointID;
    _o.RewardLevel = this.RewardLevel;
    _o.RewardInfo = this.RewardInfo.HasValue ? this.RewardInfo.Value.UnPack() : null;
  }
  public static Offset<Lobby.SA_WonderCubePointReward> Pack(FlatBufferBuilder builder, SA_WonderCubePointRewardT _o) {
    if (_o == null) return default(Offset<Lobby.SA_WonderCubePointReward>);
    var _RewardInfo = _o.RewardInfo == null ? default(Offset<Lobby.RewardData>) : Lobby.RewardData.Pack(builder, _o.RewardInfo);
    return CreateSA_WonderCubePointReward(
      builder,
      _o.WonderCubePointID,
      _o.RewardLevel,
      _RewardInfo);
  }
}

public class SA_WonderCubePointRewardT
{
  public int WonderCubePointID { get; set; }
  public sbyte RewardLevel { get; set; }
  public Lobby.RewardDataT RewardInfo { get; set; }

  public SA_WonderCubePointRewardT() {
    this.WonderCubePointID = 0;
    this.RewardLevel = 0;
    this.RewardInfo = null;
  }
}


}
