// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SN_AchievementList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SN_AchievementList GetRootAsSN_AchievementList(ByteBuffer _bb) { return GetRootAsSN_AchievementList(_bb, new SN_AchievementList()); }
  public static SN_AchievementList GetRootAsSN_AchievementList(ByteBuffer _bb, SN_AchievementList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SN_AchievementList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Lobby.AchievementData? AchievementList(int j) { int o = __p.__offset(4); return o != 0 ? (Lobby.AchievementData?)(new Lobby.AchievementData()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int AchievementListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Lobby.SN_AchievementList> CreateSN_AchievementList(FlatBufferBuilder builder,
      VectorOffset AchievementListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SN_AchievementList.AddAchievementList(builder, AchievementListOffset);
    return SN_AchievementList.EndSN_AchievementList(builder);
  }

  public static void StartSN_AchievementList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAchievementList(FlatBufferBuilder builder, VectorOffset AchievementListOffset) { builder.AddOffset(0, AchievementListOffset.Value, 0); }
  public static void StartAchievementListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<Lobby.SN_AchievementList> EndSN_AchievementList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SN_AchievementList>(o);
  }
  public SN_AchievementListT UnPack() {
    var _o = new SN_AchievementListT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SN_AchievementListT _o) {
    _o.AchievementList = new List<Lobby.AchievementDataT>();
    for (var _j = 0; _j < this.AchievementListLength; ++_j) {_o.AchievementList.Add(this.AchievementList(_j).HasValue ? this.AchievementList(_j).Value.UnPack() : null);}
  }
  public static Offset<Lobby.SN_AchievementList> Pack(FlatBufferBuilder builder, SN_AchievementListT _o) {
    if (_o == null) return default(Offset<Lobby.SN_AchievementList>);
    var _AchievementList = default(VectorOffset);
    if (_o.AchievementList != null) {
      StartAchievementListVector(builder, _o.AchievementList.Count);
      for (var _j = _o.AchievementList.Count - 1; _j >= 0; --_j) { Lobby.AchievementData.Pack(builder, _o.AchievementList[_j]); }
      _AchievementList = builder.EndVector();
    }
    return CreateSN_AchievementList(
      builder,
      _AchievementList);
  }
}

public class SN_AchievementListT
{
  public List<Lobby.AchievementDataT> AchievementList { get; set; }

  public SN_AchievementListT() {
    this.AchievementList = null;
  }
}


}
