// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Lobby
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SN_HeroExpire : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_20(); }
  public static SN_HeroExpire GetRootAsSN_HeroExpire(ByteBuffer _bb) { return GetRootAsSN_HeroExpire(_bb, new SN_HeroExpire()); }
  public static SN_HeroExpire GetRootAsSN_HeroExpire(ByteBuffer _bb, SN_HeroExpire obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SN_HeroExpire __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int HeroID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Lobby.SN_HeroExpire> CreateSN_HeroExpire(FlatBufferBuilder builder,
      int HeroID = 0) {
    builder.StartTable(1);
    SN_HeroExpire.AddHeroID(builder, HeroID);
    return SN_HeroExpire.EndSN_HeroExpire(builder);
  }

  public static void StartSN_HeroExpire(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHeroID(FlatBufferBuilder builder, int HeroID) { builder.AddInt(0, HeroID, 0); }
  public static Offset<Lobby.SN_HeroExpire> EndSN_HeroExpire(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Lobby.SN_HeroExpire>(o);
  }
  public SN_HeroExpireT UnPack() {
    var _o = new SN_HeroExpireT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SN_HeroExpireT _o) {
    _o.HeroID = this.HeroID;
  }
  public static Offset<Lobby.SN_HeroExpire> Pack(FlatBufferBuilder builder, SN_HeroExpireT _o) {
    if (_o == null) return default(Offset<Lobby.SN_HeroExpire>);
    return CreateSN_HeroExpire(
      builder,
      _o.HeroID);
  }
}

public class SN_HeroExpireT
{
  public int HeroID { get; set; }

  public SN_HeroExpireT() {
    this.HeroID = 0;
  }
}


}
